### ISSUE TITLE
No chat reports crashes game with Custom LAN enabled

### ISSUE THREAD

**Issue by Kichura** [Aizistral-Studios/No-Chat-Reports#100]
Whenever the "Edit LAN" button is pushed by the player, the game will lock up then [instantly crash](https://pastebin.com/raw/aqWQXu35).

Mods for testing:

Custom LAN v2.0.2 - 1.19 branch,
No-Chat-Reports 1.19.1-v1.7.0,
Fabric API 0.58.5.

**Comment by Kichura** [comment]
https://user-images.githubusercontent.com/68134602/181782525-bb2ab4e5-e00a-4907-b45d-85119cda798b.mp4

After updating, it seems to work now but the button itself is incorrect.

**Comment by Aizistral** [comment]
I fear that is not an issue on my side. Crash happened because I didn't update one of the methods in my mixins, it wasn't related to Custom LAN specifically.
