### ISSUE TITLE
Disable "Player Reporting" Button in Minecraft's Menu

### ISSUE THREAD

**Issue by arichornlover** [Aizistral-Studios/No-Chat-Reports#102]
I have suggested this because here's a problem with this function being enabled I can accidentally report when hitting ESC. the No Chat Reports mod will make this whole button no longer exist
![c28de2de2c3c1362604f2c0b79ad47af](https://user-images.githubusercontent.com/78001398/181409265-07dd009c-687d-4b9a-905a-52dc9ce0d309.png)

**Comment by Aizistral** [comment]
Rejected because "Player Reporting" opens Social Interactions screen, which is used for other things beyond reporting. The reporting button itself in the screen is already disabled.

**Comment by arichornlover** [comment]
Oh, sorry. Did not know that it had other stuff in there
