### ISSUE TITLE
Minecraft realms issue.

### ISSUE THREAD

**Issue by Computerlabrat** [Aizistral-Studios/No-Chat-Reports#108]
It seems like this won't allow me to connect to a friend's realm as it can't very my signature or something like that. Any ideas on a possible work around? The reason I suspect it's purely this mod is because removing it fixed it.

**Comment by Madis0** [comment]
Got another report from my modpack user. I guess the best approach would be to display the full-screen warning for the entire Realms menu, because all Realms servers would be affected anyway?

**Comment by isXander** [comment]
Note there is also no way to disable chat signing on realms as you can't access the `server.properties`

**Comment by Aizistral** [comment]
Yeah, I did not even consider how it will work with Realms. For now the only solution is to just not install the mod if you use them, going forward I will make something along the line of global warning screen @Madis0 mentions.

**Comment by Computerlabrat** [comment]
Any way to offer to toggle it off when you click the realms button with that warning screen and then turn it back on when you return to the main menu?

**Comment by Aizistral** [comment]
For now I have decided to do exactly that, Realms servers will now always be treated as unsafe. I will implement warning screen later.

**Comment by Madis0** [comment]
One player still reported issues with this in v1.8.2.

**Comment by Aizistral** [comment]
I will reopen, but we need confirmation from more than one person, and someone who would be willing to assist with testing alternative fixes if current one doesn't work.

**Comment by Madis0** [comment]
I was personally able to confirm it working, and another person (who owned the realm) was able as well. Sorry for the false alarm.
