### ISSUE TITLE
Bukkit/spigot port

### ISSUE THREAD

**Issue by Weigurde** [Aizistral-Studios/No-Chat-Reports#11]
This is already an essential mod, but I think it would be more convenient to use if it were also made as a serverside plugin for use in bukkit/spigot servers, since not all players are aware of this change even existing, let alone caring enough to change their settings over it.

**Comment by notabirb1** [comment]
Spigot and its derivatives already remove cryptographic signatures from chat messages, making chat reporting impossible. On Spigot / Paper, this mod is not necessary.

**Comment by Aizistral** [comment]
Depending on their implementation (which I'm not familiar with) messages might still be selectable for reporting, which, ideally - they shouldn't be. I am no plugin developer, but I'll pin this for future reference and discussion.

**Comment by Aizistral** [comment]
Looks like someone have made it after all: https://www.spigotmc.org/resources/noencryption.102902/

**Comment by akemin-dayo** [comment]
There's also another plugin — [No Chat Reports - Spigot](https://spigotmc.org/resources/102931) — that is more feature-complete, as it retains vanilla functionality (such as multi-language support) that is otherwise apparently broken with other plugins like the one mentioned above.

**Comment by Aizistral** [comment]
I will keep NoEncryption as a reference in project description until someone makes an agreed-upon optimal solution.

**Comment by Madis0** [comment]
There is now a wiki with instructions: https://github.com/Aizistral-Studios/No-Chat-Reports/wiki/Protecting-Server-Players
