### ISSUE TITLE
Replace Player Reporting button text

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#12]
As the client can no longer report others, but can still use the Social Interactions screen, the button text should be changed from `Player Reporting` to `Social Interactions`, aka `menu.playerReporting` to `gui.socialInteractions.title`.

Edit: this should have a separate option

**Comment by Secret-chest** [comment]
There could also be a setting in mod options to disable it.

**Comment by k9ur** [comment]
> There could also be a setting in mod options to disable it.

Disabling it would have to be reverted if a friend system is implemented.

**Comment by Secret-chest** [comment]
> > There could also be a setting in mod options to disable it.
> 
> Disabling it would have to be reverted if a friend system is implemented.

You can press P

**Comment by WVam** [comment]
In other languages, the text might not fit in the button. In fact, have you checked that it does indeed fit in the button in English?

**Comment by Madis0** [comment]
![Screenshot_20220730_143818](https://user-images.githubusercontent.com/8611110/181909189-f0b8f9d7-02bd-4604-b927-db49e7eb04cb.png)

Actually, you're right. I didn't test this and it seemed like most languages would fit but now that I had a look, there were several that wouldn't and even English kind of streches it with custom fonts.

**Comment by Aizistral** [comment]
How was that button called before chat reporting was a thing?

**Comment by Madis0** [comment]
> How was that button called before chat reporting was a thing?

It was just grayed out "Open to LAN".

**Comment by Aizistral** [comment]
No, I mean, we had social interactions screen earlier than chat reporting, right? Or wasn't it accessible via button at all?

**Comment by Madis0** [comment]
Indeed, it was only accessible with the keybind `P` initially. There is even a toast for it for fresh installs when joining multiplayer.

**Comment by Aizistral** [comment]
Ah, okay. Well, questionable naming is on Mojang anyways, seeing how player reporting is not the only thing that can be done in social interactions.
