### ISSUE TITLE
Hovering over Only Show Secure Chat button crash

### ISSUE THREAD

**Issue by kevinthegreat1** [Aizistral-Studios/No-Chat-Reports#120]
Ok, this is really weird.

caused by #117 

Game crashes when hoving over Only Show Secure Chat button **when `throw new IllegalStateException("Can't touch this");` is present in constructor in `MixinChatOptionsScreen`**

field `secureChatTooltip` doesn't get initialized in that case

### Code:

With `IllegalStateException`:

Source code:
![MixinChatOptionsScreen with IllegalStateExecption](https://user-images.githubusercontent.com/92656833/181917479-49278a54-06a0-4087-9430-1ddc974ff9c0.png)

Generated code:
![ChatOptionsScreen with IllegalStateExecption](https://user-images.githubusercontent.com/92656833/181917480-cd788d99-45cb-491c-9d29-718b46775dec.png)

Without `IllegalStateException`:

Source code:
![ChatOptionsScreen without IllegalStateExecption](https://user-images.githubusercontent.com/92656833/181917500-e4992607-de2b-4595-bb86-0fabb6ee758f.png)

Generated code:
![MixinChatOptionsScreen without IllegalStateExecption](https://user-images.githubusercontent.com/92656833/181917502-0b89fdf4-0f75-429d-826c-e0626bfc4790.png)

In the first generated code the initializer for field secureChatTooltip is **NOT** copied to the constructor.
In the second one, the initializer is present.

**Comment by Aizistral** [comment]
Very weird indeed. I typically try to avoid non-static initializers in my mixins, guess that justifies it.

**Comment by kevinthegreat1** [comment]
Welp. I didn't know that could happen. guess that's a lesson learned.
