### ISSUE TITLE
Green icon is not shown on legacy servers

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#123]
### Modloader

Fabric

### Minecraft Version

1.19.1

### Modloader Version

API 0.58.5/Loader 0.14.8

### No Chat Reports Version

1.19.1-1.8.2

### The latest.log File

irrelevant

### Bug Description

Green checkmark is not displayed on servers that clearly use a protocol older than 1.19 [(759)](https://wiki.vg/Protocol_version_numbers). I thought this was obvious that those servers should always be green...

### Steps to Reproduce

1. Join a legacy server such as Hypixel
2. Check the chat icon

### Other Information

In case you want to test and are not sure about a server's protocol, [I have a tool that can check this](https://github.com/Madis0/mc-protocol-tester/blob/main/lite.py). Note that this is not 100% accurate on hub-based servers, because the hub itself may be older than the other worlds. I'm pretty sure the game itself can get the info per-world more accurately.

**Comment by Aizistral** [comment]
I will look into it. For future reference "Modpack Info", "The latest.log File" and some other fields in the form can just be ommited. Mandatory fields are marked by * right next to them.

**Comment by Madis0** [comment]
I've asked how ViaFabric and multiconnect get the real protocol and the answer was by pinging them with protocol `-1`. If the server would respond back with some unknown value, e.g. `-1` as well, they would join with the client version.

So I guess the logic here would be to 
1. ping the servers first
2. cache the value
3. make sure the value is in a reasonable range (1-758 perhaps)
4. attempt to join 
5. user types a chat message to get the status (1.19.3)
6. if other states are valid (e.g. doesn't request signatures somehow), set the state to green.

Hopefully it could work together with mods like ViaFabric and multiconnect. Maybe NCR could ping them right at the start while the player is trying to connect?

**Comment by mrrpmrreeoow** [comment]
Please make small 1.19.2 port

**Comment by Aizistral** [comment]
> Please make small 1.19.2 port

Sorry, I don't plan to release more 1.19.2 updates unless there'd be some bugs to fix.
