### ISSUE TITLE
Velocity says "Incorrectly signed chat message" when trying to send message

### ISSUE THREAD

**Issue by Noroda** [Aizistral-Studios/No-Chat-Reports#128]
### Modloader

Fabric

### Minecraft Version

1.19.1

### Modloader Version

Fabric: Loader 0.14.8 + API 0.58.5

### No Chat Reports Version

1.19.1-v1.8.2

### Modpack Info

https://modrinth.com/modpack/sop

### The latest.log File

https://gist.github.com/Noroba-pro/e426fbe3f61a99d375b60c4a153bfa79

### Bug Description

Can't chat when using No Chat Reports mod, but without mod I can send messages

### Steps to Reproduce

1. Make a Velocity server
2. Set "force-key-authentication" to "false"
3. Connect using 1.19.1 with No Chat Reports mod
4. Try to send a message

### Other Information

can send messages on non Velocity servers

**Comment by HyperSoop** [comment]
Velocity needs an option checked to allow unsigned users/messages on the server side _i think_

**Comment by Madis0** [comment]
Latest Velocity dev build fixes this.
