### ISSUE TITLE
No longer require Velocity forceSecureProfile command line flag

### ISSUE THREAD

**Issue by mrmelon54** [Aizistral-Studios/No-Chat-Reports#13]
> To make Velocity compatible with this mod, add -Dauth.forceSecureProfiles=false to your Java command line flags (on the server side, when starting Velocity).

Seems like this can now be done with `force-key-authentication = false` in `velocity.toml`

**Comment by Aizistral** [comment]
Thanks for notifying, updated descriptions accordingly.
