### ISSUE TITLE
Bypass online block on game if banned

### ISSUE THREAD

**Issue by Danjhop4** [Aizistral-Studios/No-Chat-Reports#130]
### Idea

Add a feature to load the normal screens if banned so offline servers can still be joined by banned players this is so servers that force signing can’t ban you from the game and I would make lan work like an offline server if set by the mod

### Reasoning

To allow offline servers to be accessed by banned players

**Comment by LoganDark** [comment]
When you are banned from multiplayer, Mojang refuses to authenticate you as a premium account, so this will limit you to "cracked" or offline servers. There's nothing No Chat Reports can do about this if you've already been banned. Re-enabling the multiplayer screen though might be possible.

**Comment by Aizistral** [comment]
I have considered maintaining such feature as part of this mod, but decided against it to avoid putting NCR into the danger of being recognized as cheat software by Modrinth/CurseForge. It is very easy to implement this feature as a standalone mod, and I'm sure someone already did that.
