### ISSUE TITLE
Quilt client cannot join fabric server

### ISSUE THREAD

**Issue by moonEEVEEXwX** [Aizistral-Studios/No-Chat-Reports#132]
### Modloader

Fabric

### Minecraft Version

1.19.1

### Modloader Version

Quilt(client):Loader 0.17.2+API 4.0.0 beta1;Fabric(server):Loader 0.14.6+API 0.55.0

### No Chat Reports Version

1.19.1-v1.8.2

### The latest.log File

https://pastebin.com/fWtyd3PD

### Bug Description

When using a quilt client join an fabric server using NCR(No Chat Reports)mod,It will shows "You haven't installed No Chat Reports on Client"messages and stop the client join the game.
![QQ截图20220802122452](https://user-images.githubusercontent.com/78309411/182355116-6326b06d-cc74-42af-9be2-9fee759e046d.png)
![QQ图片20220802183849](https://user-images.githubusercontent.com/78309411/182355560-5d719bda-0206-4217-bea7-2638b240f54a.png)

**Comment by Aizistral** [comment]
Won't be an issue since 82d46ed101098f2b63c581fe4e9859737c10093b due to changes in how `demandOnClient` option works.
