### ISSUE TITLE
Issues when trying to connect to server with `enforce-secure-profile=true`

### ISSUE THREAD

**Issue by RedstoneDubstep** [Aizistral-Studios/No-Chat-Reports#143]
### Modloader

Forge

### Minecraft Version

1.19.1

### Modloader Version

Forge: 42.0.1

### No Chat Reports Version

1.19.1-v1.3.2

### The latest.log File

Client log: https://pastebin.com/bjTasu14 , server log: https://pastebin.com/ThUErjDS

### Bug Description

It is currently not possible (or at least haven't managed to do it) to join a server with `enforce-secure-profile=true`, regardless of whether the server's IP is whitelisted in NCR's config file.

### Steps to Reproduce

1. Start a Forge client with only this mod installed, and a local Forge server without any mods and the `enforce-secure-profile` property set to `true`.
2. Try to join the local server for the first time. The "Caution: Unsafe Server" screen of NCR should open, telling you about it not being able to protect you on such a server.
3. Try pressing the "Proceed" button to continue, and observe the screen continuing to open itself without letting you join the server.
4. Check the "Don't show again" checkmark and press "Proceed". This adds the server's IP to the whitelist, however you still get disconnected with a disconnection message of "Invalid signature for profile public key. Try restarting your game." or similar.
5. Go back to the server list and try to join again, and observe the same disconnection message appearing every time without you being able to join the server.

**Comment by Aizistral** [comment]
This was caused by my reliance on `ClientPlayerNetworkEvent.LoggingOut` event from Forge, which, as it turns out, is not dispatched at disconnect time as one would expect.
