### ISSUE TITLE
Technical question

### ISSUE THREAD

**Issue by Secret-chest** [Aizistral-Studios/No-Chat-Reports#148]
I'm planning to start a Bukkit server. Will a CommandHelper script that catches the chat event, immediately stops (cancels) the chat message before displaying it, then tellraws it to all users (with a custom format), disable reports?

I can't use NoEncryption, because I want to add a swear filter (only for things like mother******) and custom formatting.

**Comment by Secret-chest** [comment]
@Aizistral

**Comment by Secret-chest** [comment]
FIY the server is paper.

**Comment by Aizistral** [comment]
Yes, it's pretty much the same as `convertToGameMessage` option my mod offers.

**Comment by Secret-chest** [comment]
> Yes, it's pretty much the same as `convertToGameMessage` option my mod offers.

Ok thanks.
