### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by TempleZide** [Aizistral-Studios/No-Chat-Reports#150]
### Modloader

Fabric

### Minecraft Version

1.19

### Modloader Version

Fabric 0.14.9 and fabric-api-0.58.0+1.19

### No Chat Reports Version

NoChatReports-FABRIC-1.19-v1.2.3

### The latest.log File

https://pastebin.com/LXi5sh8Q

### Bug Description

When attempting to launch an instance the game crashes.

### Other Information

Was attempting to switch different mods in and out, eventually while tinkering with Distant Horizons I caused a crash on the PC.  Have since removed DH and gone back to bobby.  Also using Starlight.

From there I had to disable a multitude of mods after PC restart, and even Sodium required to go back to last known working settings.   Every time I attempted to launch with No Chat Reports from then on would cause the instance to crash.

**Comment by Aizistral** [comment]
Delete `NoChatReports.json` file in your `config` folder.
