### ISSUE TITLE
Error Cannot connect to the server after world loaded having NoChat with Disable Telemetry mods installed

### ISSUE THREAD

**Issue by lospejos** [Aizistral-Studios/No-Chat-Reports#151]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

Quilt Loader 0.17.2-beta.2 (qfapi-4.0.0-beta.7_qsl-3.0.0-beta.10_fapi-0.59.0_mc-1.19.2)

### No Chat Reports Version

1.19.2-v1.9.0

### The latest.log File

https://gist.github.com/lospejos/df10c4ee9fd53a37b4b98c3c6fa02aa9

### Bug Description

Startup error:

Critical injection failure: Redirector disableTelemetrySession()Z in nochatreports.mixins.json:client.MixinClientTelemetryManager from mod nochatreports failed injection check, (0/1) succeeded.

I suppose there are some incompatibilities for `NoChatReport` and `No Telemetry` mods.

### Steps to Reproduce

1. Have both `NoChatReports-FABRIC-1.19.2-v1.9.0` and `no-telemetry-1.4.0` mods installed;
2. Start Minecraft;
3. Try to load the world or create a new world in single player mode;
4. After world was loaded at 100%, error message appears: `Cannot connect to the server`.

### Other Information

I'm not sure this is a bug of this mod, sorry if I missed the repo when created a bug.

**Comment by Brottweiler** [comment]
Is No Telemetry needed with No Chat Reports? https://github.com/kb-1000/no-telemetry/issues/10

**Comment by Aizistral** [comment]
Not needed, but I main compatibility with No Telemetry in case someone wants to support that mod by downloading it anyways or including it in their modpack.
