### ISSUE TITLE
Option to display 1.19.1 instead of 1.19.84

### ISSUE THREAD

**Issue by WarpedVoxel** [Aizistral-Studios/No-Chat-Reports#155]
### Idea

I would like a toggle somewhere to make the game and window display 1.19.1 instead of 1.19.84

### Reasoning

I installed this mod to avoid chat reporting. I don't want to be reminded of it the whole time. Yes the fake version number is funny, but I would like to be able to turn it off.

**Comment by Aizistral** [comment]
Already implemented; disable `versionEasterEgg` in `NoChatReports.json`.
