### ISSUE TITLE
Spigot/Paper plugin

### ISSUE THREAD

**Issue by leofleeo** [Aizistral-Studios/No-Chat-Reports#157]
### Idea

A spigot server side plugin for no chat reports.

### Reasoning

I want to prevent chat reports on my paper server while letting nochatreports users know that this server prevents chat reports

**Comment by Aizistral** [comment]
This was discussed in #11. I am not a plugin developer and do not maintain nor plan to maintain any plugins, but there's a variety of ones people already made that fulfill the same purpose as NCR.
