### ISSUE TITLE
(Server software/plugin issue?) Kicked from 1.18.2 server when trying to send a message with NCR enabled

### ISSUE THREAD

**Issue by Synnef-8826** [Aizistral-Studios/No-Chat-Reports#160]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

Fabric 0.14.9 / Fabric API 0.59.0+1.19.2

### No Chat Reports Version

1.19.2-1.9.0 / 1.19.2-1.9.1 - 1.19.1 releases too (?)

### Modpack Info

Occurs regardless of modpack

### The latest.log File

https://paste.ee/p/lX8TZ - Server connection starts in line 502, end is Alt+F4

### Bug Description

`"NCR" as in "No Chat Reports".`
When trying to send a message in a specific server running 1.18.2 (eg. `boatsnbunnies.com`), I get kicked because of an "internal error in my connection". If I relog into the server quickly, I get an error about an internal exception with some Java code. I've gotten the exact same errors with both the Simply Optimized modpack (which features NCR) and with a fresh 1.19.2 instance using Fabric API and NCR alone. I've also tested most 1.19.1 releases of this mod and they all seem to have the same issue, and probably all previous releases do too.

I'm fairly certain both NCR and the server have something to do with the error, but I can't see what given that the server itself runs on 1.18.2, which doesn't have chat signing. My best guess, if the issue is the server's, is it's either ViaVersion (or anything similar) or any plugin that alters/modifies chat in any way. If needed I can get the list of plugins this specific server uses if it ends up being incompatibility.

Currently the only solution is to either disable NCR or have a separate instance in 1.18.2 to play.

### Steps to Reproduce

1. Join a specific 1.18.2 server (eg. `boatsnbunnies.com`) with No Chat Reports installed and enabled
2. Send a regular chat message, not a command (eg. Hi)
3. To get the other error, quickly relog into the server

### Other Information

These are the 2 errors. This one is the one that appears when I get kicked in the first place:
![image](https://user-images.githubusercontent.com/106876032/185070939-5bdd93bf-9610-4478-b457-8525583adb5b.png)
And this one occurs trying to relog too fast:
![image](https://user-images.githubusercontent.com/106876032/185070954-770e857b-d2b1-4560-9d84-16287c21d818.png)

**Comment by Aizistral** [comment]
As far as I can tell - this is the same issue as what is described in #129, or at least related. There is nothing I can do about it on my side in such case, except maybe adding a button to completely disable the mod without uninstalling it.

**Comment by Madis0** [comment]
The server is simply using an outdated version of [Velocity](https://velocitypowered.com/). You could tell the admin to update it to the latest development build as it has other networking fixes as well.

**Comment by ghost** [comment]
> The server is simply using an outdated version of [Velocity](https://velocitypowered.com/). You could tell the admin to update it to the latest development build as it has other networking fixes as well.

I'll ask, I'll update this issue with anything relevant. Thanks!

> As far as I can tell - this is the same issue as what is described in #129, or at least related. There is nothing I can do about it on my side in such case, except maybe adding a button to completely disable the mod without uninstalling it.

Looks like it, except it doesn't affect commands, only regular chat messages, probably because of version or server software (likely the latter). In any case, NCR is (supposedly) not the culprit, according to Madis. @Madis0 May I ask how you can tell it's Velocity causing the issue, in case I have to provide more information to the server admins?

**Comment by Madis0** [comment]
>  In any case, NCR is (supposedly) not the culprit, according to Madis. 

Well, NCR is related because it opts out of chat signing, but yeah not the main issue here.

> May I ask how you can tell it's Velocity causing the issue, in case I have to provide more information to the server admins?

Basically just these fixes are missing from that server, [which were pushed to Velocity upstream](https://github.com/PaperMC/Velocity/commits/dev/3.0.0): 

![Screenshot_20220818_131055](https://user-images.githubusercontent.com/8611110/185370779-e865e386-2859-46f7-a4ee-ba612c5575dd.png)

Nothing other than updating is needed to do to fix this particular issue.

**Comment by ghost** [comment]
Oh, so it's directly related to chat signing on the proxy's end, should've CTRL+F'd their repo before asking. Thanks anyway!

**Comment by LoganDark** [comment]
> May I ask how you can tell it's Velocity causing the issue

That error message, color coded red and all, is [from](https://github.com/PaperMC/Velocity/blob/6496983ca3b36db56b50cd3a9589c254460f5cfc/proxy/src/main/java/com/velocitypowered/proxy/connection/client/ClientPlaySessionHandler.java#L470-L471) [Velocity](https://github.com/PaperMC/Velocity/blob/d97ed956a7be1411b192939abcab8412932230b8/proxy/src/main/resources/com/velocitypowered/proxy/l10n/messages.properties#L27).

**Comment by Aizistral** [comment]
Closing this since issue is not on the side of NCR, and from what I know Velocity already fixed it.
