### ISSUE TITLE
Can you add an easter egg that changes the version on the title screen from 1.19.1 to 1.19.84?

### ISSUE THREAD

**Issue by dajix350** [Aizistral-Studios/No-Chat-Reports#17]

**Comment by Aizistral** [comment]
Most certainly.
![image](https://user-images.githubusercontent.com/47505981/175749543-4bdb3bca-a871-4277-8af3-29022c4d48be.png)

**Comment by asdfugil** [comment]
Do note that F3 still says 1.19.1

**Comment by CCF100** [comment]
I don't understand the easter egg

**Comment by dajix350** [comment]
> I don't understand the easter egg

People have been pointing out the similarities between Microsoft's chat reporting and the book 1984, a dystopian book about government control. It's a good read, albeit it has very dated... values.
