### ISSUE TITLE
[Enhancement] Allow versions of NCR that target 1.19.2 to load on 1.19.1 by allowing it in `fabric.mod.json` (Quilt/Fabric) and `mods.toml` (Forge)

### ISSUE THREAD

**Issue by akemin-dayo** [Aizistral-Studios/No-Chat-Reports#170]
I have tested both NCR 1.10.2 (Quilt/Fabric) and 1.4.0 (Forge) — they both seem to work fine on 1.19.1 with just the version dependency removed from the mod metadata.

No code or SDK/mapping targetting changes are required.

※ I am aware that there isn't _really_ much reason for users to remain on 1.19.1 seeing as 1.19.2 is fully protocol-compatible (protocol 760), but I do think it is worth making this change anyway for the few users that are still using 1.19.1 for… whatever reason they may have.

---

**For anyone else coming across this thread:** No, this doesn't work with 1.19. The changes between 1.19 and 1.19.1 are _significant_ to say the least, and require some work to properly backport.

**Comment by Aizistral** [comment]
Not sure how you performed your tests, but there was one backwards-incompatible change I had to make when porting to 1.19.2, in the form of this inject: https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.2-Fabric/src/main/java/com/aizistral/nochatreports/mixins/client/MixinProfileKeyPairManager.java#L37-L42. Formerly it was an inject into `profilePublicKeyData`, which no longer exists in 1.19.2.

That of course doesn't matter if you run NCR in server-only mode, but we have to keep client-sided functionality in mind too.

**Comment by akemin-dayo** [comment]
Oh, oops. Must have missed that.

Hmn, yeah then I suppose this would need to be its own separate backport branch, then — same as the eventual 1.19 backport for #61.

And yeah, I basically _only_ use NCR in client-side-only mode since I don't really join (or run…) servers that aren't running some form of Paper ;P

**Comment by Aizistral** [comment]
I can probably make do by creating injector group with older version of the inject, to make sure that depending on MC version one of them will work.

**Comment by akemin-dayo** [comment]
Just gonna leave a comment here as a reminder to port the same 1.19.1 compat changes to Forge as well: https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.2-Forge/src/main/java/com/aizistral/nochatreports/mixins/client/MixinProfileKeyPairManager.java

**Comment by akemin-dayo** [comment]
**※ EDIT:** See #182 instead.
