### ISSUE TITLE
ModMenu does not show options button in the Mod Menu

### ISSUE THREAD

**Issue by WVam** [Aizistral-Studios/No-Chat-Reports#171]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

Fabric Loader 0.14.9 + API 0.60.0

### No Chat Reports Version

1.19.2-v1.10.2

### The latest.log File

https://pastebin.com/Hxvkt8j4

### Bug Description

The options button is not displayed when selecting the mod in the Mods menu.

This is an image showing the bug:

![image](https://user-images.githubusercontent.com/83856938/187039091-8404fee1-4b27-4827-a594-5cccba736e94.png)

### Steps to Reproduce

1. Put the `.jar` files for ModMenu v4.0.6, Fabric API 0.60.0, and No Chat Reports v1.10.2 in the mods folders.
2. Launch Fabric Loader 0.14.9.
3. Click on the "Mods (53 Loaded)" button.
4. Click on "No Chat Reports"

**Expected result**: You should see a button on the top-right that allows you to access the settings menu.
**Observed result**: No such button is displayed

### Other Information

I'm using [ModMenu](https://www.curseforge.com/minecraft/mc-mods/modmenu) v4.0.6.

**Comment by Aizistral** [comment]
Did you install [Cloth Config API](https://www.curseforge.com/minecraft/mc-mods/cloth-config)?

**Comment by WVam** [comment]
No, I didn't. After instaling it, it works as expected.

Sorry for disturbing, I didn't understand that I needed to install it.
