### ISSUE TITLE
Verified Icon does not show sometimes on refresh and multiplayer menu enter

### ISSUE THREAD

**Issue by MODKILLER1001** [Aizistral-Studios/No-Chat-Reports#174]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

Fabric Loader 0.14.9 + fabric-api 0.60.0+1.19.2

### No Chat Reports Version

https://github.com/Aizistral-Studios/No-Chat-Reports/pull/172/checks

### The latest.log File

https://mclo.gs/7vSUXRD

### Bug Description

On refreshing or entering server menu sometimes verified icon does not show

**Comment by MODKILLER1001** [comment]
https://www.youtube.com/watch?v=TGzb7a-tXTw

**Comment by Aizistral** [comment]
Test in f43202a8e57f5adbbfcc86ff6994c7780a6c4c7f.

**Comment by MODKILLER1001** [comment]
Fixed
