### ISSUE TITLE
Find out how to not show warning toasts on vanilla clients

### ISSUE THREAD

**Issue by WRF5riNr** [Aizistral-Studios/No-Chat-Reports#178]
### Currently

![image](https://user-images.githubusercontent.com/47505981/183680550-d9bc58f3-f93f-4ee6-bd34-d2879bdfb96a.png)

The current solution to remove this toast is by the No Chat Reports mod on the client-side; vanilla clients will still see the toast.

### Suggestion

The ```mc.hypixel.net``` server seems to have disabled chat reports, without the toast appearing on vanilla clients, and without the "Caution: Unsafe Server" screen on clients with No Chat Reports mod. 

All chat messages on the ```mc.hypixel.net``` server appear in the chat box as server messages (not player messages), and the report button under Player Reporting is disabled with the message "This player can't be reported, because their chat messages can't be verified on this server".

(It's probably worth noting that a server with FreedomChat installed with ```ensure-secure-profile=false``` would give the same "This player can't be reported, because their chat messages can't be verified on this server" message. However, when ```ensure-secure-profile=true```, the message would instead read "No reportable messages from player <name>".)

Hence, my suggestion is to find out how to not show warning toasts on vanilla clients, similar to how the ```mc.hypixel.net``` server does.

### Reason

Most production servers of vanilla clients wouldn't want such a message to appear as it would give the player the impression of there being an issue with the server.

**Comment by Aizistral** [comment]
This is because the value of `enforce-secure-profile` can be spoofed when server converts all player messages to system messages. NCR already does this: https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.2-Fabric/src/main/java/com/aizistral/nochatreports/mixins/common/MixinServerStatus.java#L23-L35
