### ISSUE TITLE
Support for PaperMC, or other server software?

### ISSUE THREAD

**Issue by abscosmos** [Aizistral-Studios/No-Chat-Reports#18]
Hey, this is an incredible mod; I was wondering if you have plans to make a version/plugin for other server types like PaperMC, Spigot, and Bukkit?

**Comment by Ozzi-Hero** [comment]
https://github.com/Aizistral-Studios/No-Chat-Reports/issues/11

**Comment by Aizistral** [comment]
Yes, use #11 for discussion on this. I am not a plugin developer and do not have the means to implement this mod as plugin or evaluate how necessary implementing it as such even is, but I'm sure people more competent in the field will figure this out.
