### ISSUE TITLE
This server doesn't prevent chat reports

### ISSUE THREAD

**Issue by KaspianDev** [Aizistral-Studios/No-Chat-Reports#183]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

14.9 / 0.60

### No Chat Reports Version

1.6.1

### Bug Description

![image](https://user-images.githubusercontent.com/34658474/188202814-6c4143db-5f9e-46cf-9103-6474344c0073.png)
This thing shows up even if using my AntiPopup plugin and setting enforce secure chat to false, antipopup actively prevents chat reports.

**Comment by Aizistral** [comment]
This is not a bug, this is lack of compatibility. See #177. There is a way to address this with latest versions of NCR, but it will require some changes on your side: https://github.com/Aizistral-Studios/No-Chat-Reports/wiki/How-to-Get-Safe-Server-Status

**Comment by KaspianDev** [comment]
> This is not a bug, this is lack of compatibility. See #177. There is a way to address this with latest versions of NCR, but it will require some changes on your side: https://github.com/Aizistral-Studios/No-Chat-Reports/wiki/How-to-Get-Safe-Server-Status

Those apply to mods only, plugins have no mixins.

**Comment by Aizistral** [comment]
> Those apply to mods only, plugins have no mixins.

To my knowledge it depends on server software that plugin is developed for, I only mentioned Mixin because Spigot is not the only thing in town. Isn't there some kind of way to coremod the server for your case?

**Comment by KaspianDev** [comment]
> > Those apply to mods only, plugins have no mixins.
> 
> To my knowledge it depends on server software that plugin is developed for, I only mentioned Mixin because Spigot is not the only thing in town. Isn't there some kind of way to coremod the server for your case?

To be honest I don't know any server software that uses mixins apart from modded. Spigot is big majority for non modded servers, it has no mixins. For modifying the server we use NMS itself, but that is not recommended at all, everything should be done thru api.

**Comment by Aizistral** [comment]
> but that is not recommended at all, everything should be done thru api.

...so long as there is an API for what you are trying to do. I doubt there will be an API for things the kind of what NCR does anytime soon.

**Comment by KaspianDev** [comment]
Plugin message channels could be used.

**Comment by Aizistral** [comment]
How? For icon in multiplayer menu evaluation has to be done at server ping, there's just no way around it. I guess we could figure something out with safety status in actual chat screen, but I don't know how.
