### ISSUE TITLE
[Enhancement] Add a configuration option to always send secure profile key to whitelisted servers (in other words, to always treat whitelisted servers as enforcing secure profile)

### ISSUE THREAD

**Issue by akemin-dayo** [Aizistral-Studios/No-Chat-Reports#184]
It would be helpful to add an configuration option to _always_ send the user's secure profile key to any whitelisted server — in other words, to always treat whitelisted servers as enforcing secure profile.

This would avoid an undesirable situation where a user must prevent NCR from being loaded by their modloader of choice in order to join a secure-profile-enforced server that NCR is failing to detect (perhaps due to a custom disconnect reason being sent by the server), as seen in #185.

**Comment by akemin-dayo** [comment]
~~Oh, huh. I apparently can't change the labels. This should be tagged as both a bug and an enhancement.~~

**※ EDIT:** Split the issue component into #185.

**Comment by Aizistral** [comment]
> This should be tagged as both a bug and an enhancement.

It's one or another. You should make two issues in such case.

**Comment by akemin-dayo** [comment]
Split the issue component into #185.

**Comment by Madis0** [comment]
This was solved with the introduction of signing modes in the 1.19.3 version of NCR.
