### ISSUE TITLE
Errors when trying to join a server

### ISSUE THREAD

**Issue by MODKILLER1001** [Aizistral-Studios/No-Chat-Reports#190]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

Fabric loader 0.14.9/ Fabric API 0.60.0+1.19.2

### No Chat Reports Version

1.19.2-v1.11.2

### The latest.log File

https://mclo.gs/AChiAm6

### Bug Description

When trying to join a paper server with enforce secure profile enabled, it can take several tries, 95% of the time the first try doesn't work, the 2nd time is 50%, third time is usually a charm 

### Steps to Reproduce

Get an instance with FAPI 0.60.0+1.19.2, and NCR 1.19.2-v1.11.2
Try to join a server running [paper 1.19.2 # 141](https://papermc.io/downloads). that has enforce secure profile enabled. You will get error messages like these 
![image](https://user-images.githubusercontent.com/17520451/189565848-e275918e-9586-4f59-9b0e-bc256bce1551.png)
![image](https://user-images.githubusercontent.com/17520451/189565859-128bdfb5-a0a1-46a8-aedb-a7b03d748fed.png)
![image](https://user-images.githubusercontent.com/17520451/189565868-f9cfaab1-7b0f-4fef-aa9d-6564b9b438af.png)

**Comment by MODKILLER1001** [comment]
The java util Map get Object null is the most common message, with index out of bounds the second most common, and plain java lang NullPointerException the third most common.

Also note I did add the server to the whitelist to allow it.

**Comment by Madis0** [comment]
Getting this error:
![](https://cdn.discordapp.com/attachments/992979156767883375/1018900836920868885/unknown.png)

* on Paper builds 141 and 142
* signing enforced
* whitelisted (joining player not in whitelist)

The test was conducted on a "real" server, aka not localhost.

Cannot reproduce on vanilla server though:

![](https://cdn.discordapp.com/attachments/1002683819524112576/1018904312824467586/unknown.png)

Edit: on a second try I cannot reproduce it on Paper either... :roll_eyes:

**Comment by MODKILLER1001** [comment]
![image](https://user-images.githubusercontent.com/17520451/189698372-e185f8c9-d6b9-4f36-96aa-4b55ca27d701.png)
is for NCR, we havent been able to reproduce the other 2 errors. This also happened when the player was whitelisted.

**Comment by MODKILLER1001** [comment]
This is the DNS setup for the server i keep having the most issues on, pineapplecraft is just a name i made up
![image](https://user-images.githubusercontent.com/17520451/190922537-820ec5ae-2a37-403d-ab46-57eb29015356.png)

**Comment by MODKILLER1001** [comment]
related to #160 possibly as same kick message
paper - yes
whitelist - yes
signing - yes

**Comment by Aizistral** [comment]
Alright, so, as far as I can tell this is some kind of weird throttling. As much as I tested waiting for a few seconds between reconnects seems to reliably fixes the issue.
In that light NCR now has a delay before automatic reconnects. By default it is 4 seconds, but can be adjusted in config.

**Comment by Madis0** [comment]
I could still reproduce it with v1.13.8, even if NCR waits for the reconnect... :(
On some tries it displays the vanilla error message instead (missing signing key blah blah).

**Comment by Aizistral** [comment]
Try to increase waiting time.
