### ISSUE TITLE
Explain enforce-secure-profile

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#2]
> Server will relay them unless "enforce-secure-profile" option is set to true in server options, in which case it will not let you join.

If I understand this correctly, this paragraph is about whether a 1.19 server has toggled an option in server.properties. 

In that case, what is the message the client receives when trying to join it? Assuming it is a cryptic error message, could you add an explanatory one?

**Comment by 0-x-2-2** [comment]
Enable it and try it out, it allows non-Microsoft accounts to join your server and players who disabled public key signing. You can see how this was implemented in a third party proxy that also enables this feature by default: https://github.com/PaperMC/Velocity/blob/1a1391a51916b111ceafe47bfbb144cf63cdc7ac/proxy/src/main/java/com/velocitypowered/proxy/connection/client/InitialLoginSessionHandler.java#L86

**Comment by Madis0** [comment]
> Enable it and try it out, it allows non-Microsoft accounts to join your server and players who disabled public key signing. You can see how this was implemented in a third party proxy that also enables this feature by default: https://github.com/PaperMC/Velocity/blob/1a1391a51916b111ceafe47bfbb144cf63cdc7ac/proxy/src/main/java/com/velocitypowered/proxy/connection/client/InitialLoginSessionHandler.java#L86

So, from that source it seems to use one of those vanilla strings:

> Invalid signature for profile public key.
> Try restarting your game.

> Unable to parse profile public key.

> Missing profile public key.
> This server requires secure profiles.

That can get confusing with this mod, so I still propose changing this to something more explanatory.

**Comment by Aizistral** [comment]
> In that case, what is the message the client receives when trying to join it? 

By default - this:
![invalidsignature](https://user-images.githubusercontent.com/47505981/174998254-51a146b7-1035-4b34-8642-9da58f67536e.png)

> That can get confusing with this mod, so I still propose changing this to something more explanatory.

Reasonable idea. I will.

**Comment by Aizistral** [comment]
Closing this since instead I will eventually implement warning-based proceed-or-leave screen, see #4.
