### ISSUE TITLE
Does not work on 1.19.1-rc1 (fabric)

### ISSUE THREAD

**Issue by colewass** [Aizistral-Studios/No-Chat-Reports#20]
When trying this out in 1.19.1-rc1 (fabric) the game fails to open. Here's a link to my logs:
https://paste.ee/p/EsrvC

**Comment by Madis0** [comment]
You need Fabric API.

**Comment by Aizistral** [comment]
Yes, first - you need that. Second - the mod doesn't officially support 1.19.1 RC; it will most likely work, but there are a couple important changes that will be introduced as part of official release for 1.19.1.
