### ISSUE TITLE
All of the UI pertaining to the new Chat Encryption feature are cut off on most common display resolutions, including 1920x1080 and 3456x2160.

### ISSUE THREAD

**Issue by akemin-dayo** [Aizistral-Studios/No-Chat-Reports#200]
## Environment
**Modloader:** quilt-loader 0.17.4
**Minecraft Version:** 1.19.2, 1.19.1
**No Chat Reports Version:** 1.13.0

## Bug Description
All of the UI pertaining to the new Chat Encryption feature are cut off on most common display resolutions, including 1920x1080 and 3456x2160.

This includes both "About Encryption" _and_ "Encryption Settings".

It would probably be a good idea to decrease the amount of padding between each line, or something like that.

### 1920x1017@4x (Windowed mode on Windows)
![framebuffer](https://user-images.githubusercontent.com/1980487/192172468-cdb4528e-7599-434a-aa4b-b09dba44f708.png)

### 1920x1080@4x (Fullscreen)
![framebuffer](https://user-images.githubusercontent.com/1980487/192172302-1fee6498-e64a-40ce-9e7e-1734bcaeaa5f.png)

### 3456x1974@8x (Windowed mode on macOS)
![framebuffer](https://user-images.githubusercontent.com/1980487/192172676-25cba9fb-c68b-46b5-803f-3053c8c63871.png)

### 3456x2160@8x (Fullscreen)
![framebuffer](https://user-images.githubusercontent.com/1980487/192172700-be01f0db-efc8-4ad4-89e7-e507dbb94079.png)

### 1920x1017@4x (Windowed mode on Windows)
![framebuffer](https://user-images.githubusercontent.com/1980487/192173472-4f1c9783-efc1-409b-9fdb-98930967845b.png)

### 1920x1080@4x (Fullscreen)
![framebuffer](https://user-images.githubusercontent.com/1980487/192173481-f470d970-d334-4d94-9ed7-a8a1c962df77.png)

### 3456x1974@8x (Windowed mode on macOS)
![framebuffer](https://user-images.githubusercontent.com/1980487/192173122-a8000f0f-be75-4333-a516-2971c7398fcf.png)

### 3456x2160@8x (Fullscreen)
![framebuffer](https://user-images.githubusercontent.com/1980487/192173144-abb13ee9-78d5-48db-948b-f18364561598.png)

**Comment by Aizistral** [comment]
Does anyone really play with 4x scaling?

**Comment by akemin-dayo** [comment]
I do ;P

Myself aside, most people probably don't change the default UI scaling setting from "0" (Auto) anyway, which means Minecraft will always default to the largest UI scale possible.

**Comment by Aizistral** [comment]
Fine, I'll find a way to fix this.

**Comment by akemin-dayo** [comment]
Hmn, I'm noticing some odd behaviour even after 907df117f0e3312270f23b8a93bda2084468ac53.

If the UI scaling option is left at the default of 0 (Auto) for 3456x1974, it seems that _specifically_ the "Encryption Settings" view does not go into "huge UI" mode. The "About Encryption" view appears to be unaffected, at least in my testing.

If you explicitly set a UI scale of 7 or 8 in the settings, then everything behaves as expected.

**Comment by Aizistral** [comment]
This doesn't make any sense, both screens use absolutely identical calculation for whether or not they should go into huge mode. What NCR version did you test this with, and are you sure that auto is actually equal to 7 or 8?

**Comment by akemin-dayo** [comment]
> What NCR version did you test this with

I've tested this with NCR 1.13.4 and 1.13.2.

> are you sure that auto is actually equal to 7 or 8?

I have not _programmatically_ verified this, but "Auto" does at least appear _visually_ identical to both 7 and 8. (※ When the Unicode font is enabled, all odd-number UI scales become equivalent to their +1 value.)

> both screens use absolutely identical calculation for whether or not they should go into huge mode

I was also thinking this was the case (given `hugeGUI()` in the code), but I… don't have any other explanation for what I'm seeing.

I'll try adding some debug logging for `hugeGUI()` later when I have time to see what's going on.

---

## Screenshots
### "About Encryption" displaying correctly at 0 UI scale
![framebuffer](https://user-images.githubusercontent.com/1980487/192859857-45e85e29-ea2b-44dd-98ef-f3abb7242926.png)

### "Encryption Settings" somehow _not_ going into huge UI mode at 0 UI scale
![framebuffer](https://user-images.githubusercontent.com/1980487/192860100-9289bea8-e4f7-4bd0-b5f7-c9c6655f79ac.png)

### UI scale of 0 (Auto)
![framebuffer](https://user-images.githubusercontent.com/1980487/192860675-4d66b018-757b-4665-a66f-7c32d130f4a0.png)

### UI scale explicitly set to 8
![framebuffer](https://user-images.githubusercontent.com/1980487/192860715-b39a9d6d-69a5-47b7-8ffd-f875e4a922ba.png)

### … and now "Encryption Settings" works correctly when set explicitly to 8 (or 7 — the scaling is identical)
![framebuffer](https://user-images.githubusercontent.com/1980487/192861074-e53faeb3-6a41-4e5e-8844-63fef5373a74.png)

**Comment by Aizistral** [comment]
Really weird. The only explanation I see is if screen height somehow is not calculated correctly in the case of settings screen, but I have no idea why it would go wrong with that screen specifically and not the other one.

**Comment by Aizistral** [comment]
Ahhhhh I got it. I goes into huge mode, I just didn't check it correctly where line height is calculated...

**Comment by Aizistral** [comment]
Test in v1.13.5, should be fixed.

**Comment by akemin-dayo** [comment]
Can confirm, the issue is now fully fixed as of eafe2c815bfd7a383fc94b6c6a261395bc4b0246 / 1.13.5.
