### ISSUE TITLE
[Enhancement] Add an option to hide the "Encryption" button.

### ISSUE THREAD

**Issue by akemin-dayo** [Aizistral-Studios/No-Chat-Reports#201]
It would be nice to add an option to hide the "Encryption" button from the chat view for:

* Those who do not plan on using it (like myself)
* Those who play on servers where the Encryption feature either does not work (which is any server that converts player messages to system messages), or is otherwise entirely unnecessary

**Comment by Aizistral** [comment]
It does work with message coversion, at least if message decoration correctly mirrors such for player messages. I have specifically tested that with NCR's own implementation of the feature.
Furthermore, the option already exists. It's called `showEncryptionButton` and is located in `.minecraft/config/NoChatReports/NCR-Encryption.json`.

**Comment by akemin-dayo** [comment]
Ah, sorry about that — I was being dumb and only checked `NCR-Client.json` like an idiot l o l

> It does work with message coversion, at least if message decoration correctly mirrors such for player messages. I have specifically tested that with NCR's own implementation of the feature.

Oh, wasn't aware of that. What I've found is that it obviously doesn't work with servers that use some kind of third party chat plugin, like EssentialsX + Multiverse-Core. Didn't really expect it to work anyway, especially since they rewrite the chat format entirely (`[Worldname]<UsernameOrNickname>Message`), so it would be impossible for NCR (or at least, the current version of NCR — not sure if you want to go through the trouble of adding every custom chat format out there) to detect those as player messages.

**Comment by Aizistral** [comment]
It wouldn't be impossible, I just have to account for the format of those particular plugins. I will add additional debug logging to help analyze the structure of converted messages in the next update. When it's out you could test how different converting plugins interact with encryption and submit your results in a separate issue.

**Comment by Aizistral** [comment]
Done in 1.19.2-v1.13.2. With debug log enabled, when your client receives any chat message you should see `Adding chat message, structure:` followed by jsonified message in client logs.
