### ISSUE TITLE
[Enhancement] Encryption compatibility with custom chat formats

### ISSUE THREAD

**Issue by akemin-dayo** [Aizistral-Studios/No-Chat-Reports#204]
This is a _really_ low priority enhancement, but it would be nice if it would be possible for users to define their own custom chat formats for those who want to use the chat encryption feature on servers that use a custom chat format (and convert player messages to system messages).

**Here's some examples I've collected:**
* EssentialsX public chat: `<UsernameOrNickname> MessageContents`
	* `{"extra":[{"text":"<"},{"color":"red","text":"Karen/あけみ"},{"text":"> a"}],"text":""}`
* EssentialsX `/msg` DM (sending): `[me -> RecipientUsernameOrNickname] MessageContents`
	* `{"extra":[{"bold":false,"color":"gold","italic":false,"obfuscated":false,"strikethrough":false,"text":"[","underlined":false},{"color":"red","italic":false,"text":"me"},{"color":"gold","italic":false,"text":" -> "},{"color":"red","italic":false,"text":"Karen/あけみ"},{"color":"gold","italic":false,"text":"] "},{"italic":false,"text":"a"}],"text":""}`
* EssentialsX `/msg` DM (receiving): `[SenderUsernameOrNickname -> me] MessageContents`
	* `{"extra":[{"bold":false,"color":"gold","italic":false,"obfuscated":false,"strikethrough":false,"text":"[","underlined":false},{"color":"red","italic":false,"text":"Karen/あけみ"},{"color":"gold","italic":false,"text":" -> "},{"color":"red","italic":false,"text":"me"},{"color":"gold","italic":false,"text":"] "},{"italic":false,"text":"a"}],"text":""}
`
* EssentialsX + Multiverse public chat: `[World]<UsernameOrNickname> MessageContents`
	* `{"extra":[{"color":"white","text":"Creative"},{"color":"white","text":"]"},{"text":"<"},{"color":"red","text":"Karen/あけみ"},{"text":"> a"}],"text":"["}`
* Very customised VentureChat public chat: `[ProxyBackendServerPrefix | VentureChatChannel] UsernameOrNickname: MessageContents`
	* `{"extra":[{"extra":[{"color":"white","text":""},{"color":"dark_gray","text":"["},{"color":"yellow","text":"L "},{"color":"white","text":""},{"bold":true,"color":"white","text":"| "},{"color":"dark_green","text":"Global"},{"color":"dark_gray","text":"]"},{"color":"white","text":""},{"clickEvent":{"action":"run_command","value":"/help"},"color":"white","hoverEvent":{"action":"show_text","contents":{"extra":[{"text":""}],"text":""}},"text":""},{"color":"white","text":" "},{"clickEvent":{"action":"suggest_command","value":"/msg akemin_dayo"},"color":"white","hoverEvent":{"action":"show_text","contents":{"extra":[{"color":"gold","text":"Username: "},{"color":"white","text":" akemin_dayo"}],"text":""}},"text":"akemin_dayo"},{"color":"white","text":""},{"color":"dark_green","text":":"}],"text":""},{"color":"white","text":""},{"color":"white","text":" a"}],"text":""}`

**Comment by Aizistral** [comment]
I think I can take a more universal apprroach, now that commonalities in those custom formats are apparent.

**Comment by Aizistral** [comment]
From my understanding most custom chat formats should now be compatible with encryption, but I ask that you redo your tests with v1.13.4, just in case.

**Comment by akemin-dayo** [comment]
I can confirm that after 32384f27c63106469e32fc2e77e9b09b90581d55, chat encryption now works with all the custom chat formats listed above!
