### ISSUE TITLE
False "unsafe server" flagging?

### ISSUE THREAD

**Issue by KaspianDev** [Aizistral-Studios/No-Chat-Reports#213]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

14.9 / 0.62

### No Chat Reports Version

1.19.2-v1.13.5

### Bug Description

In this scenario i used MCC Island server.
Without the mod joining the server sends that "unsafe server" popup bullshit
With the mod I get message below
![image](https://user-images.githubusercontent.com/34658474/194120324-ce0428ed-63fe-48d9-8613-7538197f7f16.png)
It doesn't sound quite right to me because of the popup, feel free to correct me.

### Steps to Reproduce

1. Join play.mccisland.net with the mod
2. That's it

**Comment by Aizistral** [comment]
It all depends on server configuration. While it's not possible in vanilla, server can, in principle, demand players to send signed messages without making itself obliged to actually relay them to everyone with those signature intact. There is nothing NCR can do about that.

**Comment by KaspianDev** [comment]
Could we at least force it to work on certain server?

**Comment by Aizistral** [comment]
Depends on what you mean by that. I don't see a point to make any adjustments here since server demanding signatures **is** inherently unsafe, whether it shows those signatures to most players or not. So this is not a "false warning".

**Comment by Madis0** [comment]
> Could we at least force it to work on certain server?

Well, you can join the server by simply accepting the warning, if that's what you asked. And you can disable the full-screen warning entirely in settings by setting "all servers to whitelist" or something like that.
