### ISSUE TITLE
Caesar encryption results in "Illegal characters in chat"

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#216]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

Fabric Loader 0.14.9, API 0.62.0

### No Chat Reports Version

1.13.6

### Bug Description

Setting Caesar's "encryption key" to 90 will kick the player out on chat.
![image](https://user-images.githubusercontent.com/8611110/194360528-afa0c37c-539f-4346-b1b9-df3783680f9a.png)

### Steps to Reproduce

1. Go to a singleplayer world
2. Enable chat encryption: Caesar cipher, 90 as the "key", encrypt public messages checked
3. Try to chat

### Other Information

Perhaps you just didn't check if the shifted value is within game's supported Unicode range.

**Comment by Aizistral** [comment]
It's not about supported range, it's just that some specific characters are disallowed in chat. See `SharedConstants#isAllowedChatCharacter`.
