### ISSUE TITLE
Forge feature parity

### ISSUE THREAD

**Issue by wendall911** [Aizistral-Studios/No-Chat-Reports#218]
### Idea

I see that the mod is not setup with a multi-loader repo, but maintains two separate branches. This is just an inquiry to see if any help is needed for either:

1. Creating a new branch for 1.19 that uses a multi-loader template, incorporating all features into one releasable codebase
2. Migrating features into Forge branch

I have a couple mods currently that use multi-loader templates, but most recently, setup with https://github.com/wendall911/ChargedCharms

Looking at the code, I can probably follow the same style, and other than I don't use Window or tabs (unless forced to do so, lol)

### Reasoning

Would be good for users of both loaders to get equal benefits out of this. Looking at downloads per release, looks like both could equally benefit from feature parity.

### Other Information

Since this wasn't as simple as just providing a PR, and I have no idea what the preferred method of contact is for @Aizistral I figured I'd put this here as a suggestion and see what comes of this. Let me know what you think. I'd be happy to take the conversation out of this issue if you'd like to discuss.

**Comment by Aizistral** [comment]
I will try to set up ChargedCharms locally to see whether that multiloader approach would be worth it. In the meantime you can join my Discord server and hang in **#no-chat-reports** channel, so that I can inquire you directly when necessary: https://discord.gg/fuWK8ns

**Comment by Aizistral** [comment]
Closing this since we arrived at the conclusion that multiloader template is not suitable for this project. I've messaged you @wendall911 regarding Forge branch maintenance on Discord, but received no reply, so I suppose that's something I'll have to keep doing myself.
