### ISSUE TITLE
Encrytion menu is too zoomed in on 1440p

### ISSUE THREAD

**Issue by TroubledPerson** [Aizistral-Studios/No-Chat-Reports#220]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

fabric loader version = 0.14.9

### No Chat Reports Version

1.19.2 v1.13.8

### Bug Description

the selection bars at the bottom go past the screen

### Steps to Reproduce

open the encrytion menu in 2560 x 1440 resolution

**Comment by Aizistral** [comment]
Specify your GUI scale and send a screenshot.

**Comment by TroubledPerson** [comment]
![BUG](https://user-images.githubusercontent.com/89006981/194511135-57d573df-e26f-45a1-b346-fc1592c291b1.png)
![2022-10-07_19 37 12](https://user-images.githubusercontent.com/89006981/194511261-41970906-19a1-4d43-a22a-441793780bed.png)

**Comment by Aizistral** [comment]
I don't see where GUI scaling wold be in that second screenshot. Check graphics settings

**Comment by TroubledPerson** [comment]
![BUG2](https://user-images.githubusercontent.com/89006981/194511953-58c386ef-70d5-4e92-a7ab-a0756a6ddf9c.png)
[RetroBar.64-bit.zip](https://github.com/Aizistral-Studios/No-Chat-Reports/files/9732205/RetroBar.64-bit.zip)

**Comment by TroubledPerson** [comment]
I accidently sent a useless zip just ignore it

**Comment by TroubledPerson** [comment]
just tested it with no texture pack. it has the same effect
