### ISSUE TITLE
Issues with special chars in encryption

### ISSUE THREAD

**Issue by onebyte4** [Aizistral-Studios/No-Chat-Reports#224]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

Fabric Loader v0.14.9 + Fabric Api v0.62.0+1.19.2

### No Chat Reports Version

1.19.2-v1.13.8

### Bug Description

chars like this only works on Caesar Encryption : á ß ü ÿ 
korean,japanese,chinese not work correctly in any encryption algorithm: 

examples:
こんにちは
你好呀
안녕

some other special chars also not work correctly on any encryption algorithm : ✘✭✪

**Comment by Aizistral** [comment]
I have tested those first 4 characters with every encryption algorithm (in the order of button cycle), and they seem to work correctly at all times:
![image](https://user-images.githubusercontent.com/47505981/194727713-55ce5ebe-2169-4046-9dc2-8f93fa96485d.png)

Korean, japanese and chinese seem to not work specifically in Caesar, not any other algorithm:
![image](https://user-images.githubusercontent.com/47505981/194727813-38b801e0-f692-4589-ad2d-63c6748b7d26.png)

Same for special symbols:
![image](https://user-images.githubusercontent.com/47505981/194727851-582077c7-25cc-441e-a377-c66aa7d7546a.png)

**Comment by onebyte4** [comment]
![bugreport](https://user-images.githubusercontent.com/79567896/194728575-e46d003a-7e8b-4e85-9867-2a49287446a9.PNG)

 á ß ü ÿ  changes to question mark in squares but "こんにちは" "你好呀" "안녕" changes to ? 

maybe this issue caused by encoding on encryption?

**Comment by Aizistral** [comment]
Yes, this does seem to be encoding-related. What is default encoding on your client? You can run this version of NCR and look for `Default JVM text encoding is:` line in the logs to find out: https://aizistral.com/NoChatReports-FABRIC-1.19.2-v1.13.9_debug.jar

**Comment by onebyte4** [comment]
update: putting -Dfile.encoding=UTF-8 to jvm arguments fixes issue except caesar

**Comment by Aizistral** [comment]
> update: putting -Dfile.encoding=UTF-8 to jvm arguments fixes issue except caesar

Quite as expected. I still need to know what default encoding is in your case to test things with it though.

**Comment by onebyte4** [comment]
>Default JVM text encoding is: windows-1254
