### ISSUE TITLE
Server Cant start

### ISSUE THREAD

**Issue by Icedragonzz821** [Aizistral-Studios/No-Chat-Reports#226]
### Modloader

Forge

### Minecraft Version

1.19.2 

### Modloader Version

43.1.33

### No Chat Reports Version

1.19.2 v1.4.0

### Modpack Info

https://www.curseforge.com/minecraft/modpacks/inclusive-ii

### Bug Description

The server gets stuck on loading the mixins and never starts.

### Steps to Reproduce

1. Start server
2. Wait
3. Get mixin error

### Other Information

NA

**Comment by Aizistral** [comment]
Please attach the logs.

**Comment by helscarthe** [comment]
I feel like since this is already here, I shouldn't open another issue. But this happened to me too, except on fabric, on a completely custom made pack. Logs here: https://mclo.gs/VxthNUz

**Comment by Aizistral** [comment]
Closing this since no reply followed.
