### ISSUE TITLE
Address the possibility of slurs appearing in encrypted text

### ISSUE THREAD

**Issue by Aizistral** [Aizistral-Studios/No-Chat-Reports#237]
### Idea

The odds of that are fairly low, but not astronomically low apparently, especially for short ones. The obvious solution would be to include a filter, but I think we can do better than that by simply shifting all encrypted messages away from the alphabet and into special symbols.

### Reasoning

Would be ironic to get framed by your own encryption.

**Comment by Secret-chest** [comment]
What if you use symbols in your messages?

**Comment by Aizistral** [comment]
> What if you use symbols in your messages?

How is that relevant?

**Comment by Madis0** [comment]
> How is that relevant?

I believe they are asking for whether any used symbols are being shifted back to letters.

**Comment by Aizistral** [comment]
No, that's not how it works. Shifting will be applied on top of Base64 encoding, and Base64 always produces text with a fixed set of 64 symbols, most of which are latin letters.

Caesar is a different case, but there you can just use high enough shift value to get out of range of symbols your language uses (whatever it is). Unless your message is composed entirely of special symbols with shift values deliberately picked such that those symbols will be shifted into some foreign alphabet (it will always be foreign, since latin letters are the lowest symbol set accessible for use in Minecraft chat) - you're safe.
