### ISSUE TITLE
Bump Fabric API dependency

### ISSUE THREAD

**Issue by Aizistral** [Aizistral-Studios/No-Chat-Reports#239]
### Idea

Bump Fabric API dependency.

**Comment by Madis0** [comment]
We could now also change "fabric" to "fabric-api" for clarity in fabric.mod.json, even though it doesn't really matter if the required part is bundled anyway. 
(For context, it's the new name for it since 1.19.2, though "fabric" is still allowed for backwards-compatibility.)

**Comment by Aizistral** [comment]
> We could now also change "fabric" to "fabric-api" for clarity in fabric.mod.json, even though it doesn't really matter if the required part is bundled anyway.

We do not depend on Fabric API directly since #135 was merged, there's now a specific list of modules listed as dependencies:

```json
"depends": {
    "fabricloader": ">=0.14.6",
    "fabric-networking-api-v1": "*",
    "fabric-screen-api-v1": "*",
    "fabric-rendering-v1": "*",
    "fabric-resource-loader-v0": "*",
    "minecraft": [ "=1.19.1", "=1.19.2" ],
    "java": ">=17"
  }
```

**Comment by Madis0** [comment]
You're right, I must've looked at the file on a wrong branch or something.
