### ISSUE TITLE
22w42a update please!

### ISSUE THREAD

**Issue by wh0oo** [Aizistral-Studios/No-Chat-Reports#241]
### Idea

Please please reconsider, and let us have an update to 22w42a, please?  

### Reasoning

Many of us would love to use 22w42a and use your mod!

**Comment by Madis0** [comment]
Reconsider what? Aizistral has yet to investigate the changes done in the snapshot, and there are some fixes that need to be implemented on 1.19.2 first. 

I believe there will be a snapshot build (maybe for next snapshot etc) at some point though, just be patient.

**Comment by Aizistral** [comment]
@Madis0 
![image](https://user-images.githubusercontent.com/47505981/197505623-333dd6e8-e696-4149-a23d-6af5b61a6086.png)

Snapshot build will most likely not be possible due to other priorities I have to focus on.
