### ISSUE TITLE
public key and /msg based group chats

### ISSUE THREAD

**Issue by dallytaur** [Aizistral-Studios/No-Chat-Reports#243]
### Idea

Could you use /msg as a way to send hidden chat messages to group parties then all you need to do is add a whitelist of people to make a then use the mod as a hidden message channel that could be used for the public key to send the key safely.

you send encoded /msg to everyone in the group with and then they send there back with and clean up formatting from sending it as /msg

this also allows for private group charts that

### Reasoning

It will hide all the messages from the main chat and the encoding will keep It out of the server owner's hands also

public key would allow sharing of passphrases over the chat without third-party channel

**Comment by Madis0** [comment]
You'll probably get punished by server admins for typing commands too fast/too often in this case...

**Comment by Aizistral** [comment]
I will not be implementing group chats this way, but they might make an appearance in a different form if I ever add a service for exchanging messages off the server. Regarding public key - see #234.

**Comment by Secret-chest** [comment]
> I will not be implementing group chats this way, but they might make an appearance in a different form if I ever add a service for exchanging messages off the server. Regarding public key - see #234.

Please no. This mod is for fixing chat, not replacing it. It's too much.

**Comment by Aizistral** [comment]
> Please no. This mod is for fixing chat, not replacing it. It's too much.

All extra features are optional. Don't use if you don't like.

**Comment by Secret-chest** [comment]
> > Please no. This mod is for fixing chat, not replacing it. It's too much.
> 
> All extra features are optional. Don't use if you don't like.

@Aizistral but why not make a separate mod?

**Comment by Aizistral** [comment]
Because maintaining multiple one-feature mods would be a lot harder than one mod with all the features, not to mention informing people that all these features even exist as separate mods.

**Comment by Secret-chest** [comment]
> Because maintaining multiple one-feature mods would be a lot harder than one mod with all the features, not to mention informing people that all these features even exist as separate mods.

I want a no-nonsense simple solution that does only what I want to. So _it's forking time?_

**Comment by Aizistral** [comment]
> I want a no-nonsense simple solution that does only what I want to. So it's forking time?

Well, that's why the project is open-source. If you want it to follow a different paradigm then by all means, go ahead and make it happen.
