### ISSUE TITLE
Encrypted Message displays as encrypted string even to self

### ISSUE THREAD

**Issue by CubityFirst** [Aizistral-Studios/No-Chat-Reports#248]
### Modloader

Quilt

### Minecraft Version

1.19.2

### Modloader Version

Fabric Loader 0.14.10 / Fabric API 0.64.0+1.19.2 & Quilt 0.17.6

### No Chat Reports Version

1.19.2-v1.13.10

### Modpack Info

MultiMC Export - https://i.cubityfir.st/Test%20for%20NCR%20%28Fabric%29.zip

### The latest.log File

https://gist.github.com/CubityFirst/83e562e488d2fccca63ffd3e941658df

### Bug Description

When you send a message in chat with encryption turned on, under any cypher displays in chat as the encrypted string.

### Steps to Reproduce

1. Load Game
2. Make sure encryption is turned on.
3. Send Message.
4. Look at chat.

**Comment by Aizistral** [comment]
Specify what algorithm and key you tested this with and what specific messages you tried to send.

**Comment by CubityFirst** [comment]
It was experienced with all algorithms and keys. This was a fault with a plugin on the server.

The debug log version of this log > https://gist.github.com/CubityFirst/842b5203216b3c8816fcf1ebd859dbcc

The two mods that are most likely to impact this (that when I removed, fixed the problem)
https://modrinth.com/mod/styled-nicknames
https://modrinth.com/mod/styled-chat
