### ISSUE TITLE
Encryption should avoid "§"

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#250]
### Idea

Encryption should avoid using the paragraph sign `§` on Caesar or similar shifts.

### Reasoning

Because typing that to chat will kick the player and players are not able to normally use it anyway https://bugs.mojang.com/browse/MC-1572

### Other Information

I don't know if this is an issue in the current implementation at all, posting it just in case

**Comment by Aizistral** [comment]
It already avoids.
