### ISSUE TITLE
Implement stealth mode

### ISSUE THREAD

**Issue by Aizistral** [Aizistral-Studios/No-Chat-Reports#255]
### Idea

Add some kind of option to completly hide presence of No Chat Reports on client from server.

### Reasoning

While NCR uses dedicated networking channel to establish its own presence on either side when respective config options demand it, it can be abused by servers to "block" the mod, preventing the client from joining the server unless mod toggle is turned off. Having such option would provide a more convenient way to circumvent that.

**Comment by Madis0** [comment]
What would this option actually do? The users can already disable the "safe" indicator communication, or the signature disabling with the overall mod toggle.

**Comment by Aizistral** [comment]
> What would this option actually do? The users can already disable the "safe" indicator communication, or the signature disabling with the overall mod toggle.

It would disable the use of networking channel specifically. That channel is not relevant for safety status evaluation, nor for signature disabling.

**Comment by Madis0** [comment]
Besides a separate global toggle (which is good), how about also applying stealth mode automatically to all whitelisted servers? Because once a server enforces signatures, it probably doesn't like NCR anyway 😄

**Comment by Aizistral** [comment]
Yeah, makes sense.
