### ISSUE TITLE
Incorrect tooltip on toggling the mod

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#262]
### Modloader

Fabric

### Minecraft Version

22w44a

### Modloader Version

Fabric Loader 0.14.10, bundled FAPI

### No Chat Reports Version

22w44a-v1.14.0

### Bug Description

NCR for 1.19.3 changed the unknown tooltip from:
> No Chat Reports was toggled mid-session. Server safety status can only be evaluated on login. Please re-join the server to evaluate its safety status.

to

> No Chat Reports is not sure about safety of this server yet. Try to send a message in chat in order to evaluate it.

This is wrong, both tooltips should be there and displayed in different times. 
Edit: though the original tooltip also needs adjusted wording.

### Steps to Reproduce

_P.S. First step isn't reproducible in v1.14.0 yet, due to disabled Cloth Config and Mod Menu APIs._

Reproduce 1:
1. Disable NCR from server list button
2. Join a server
3. Enable NCR from Mods -> No Chat Reports -> :gear: -> Technical -> Enable mod
4. Hover at the chat status icon

Reproduce 2:
1. Join a server
2. Hover at the chat status icon

**Comment by Aizistral** [comment]
Effectively fixed in bad639e9dad8d7c6d8aafcff6de7e13aa31c556e.
