### ISSUE TITLE
Translation platform

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#265]
### Idea

Since No Chat Reports is getting a lot of strings and a lot of translators, it would be wise to migrate to a translation platform to make the process easier for everyone.

Some platforms:
- Crowdin - [free limited plan](https://crowdin.com/pricing)/[free unlimited FOSS plan](https://crowdin.com/page/open-source-project-setup-request)
- Transifex - [free FOSS plan](https://www.transifex.com/open-source/)
- Weblate - [free FOSS plan](https://hosted.weblate.org/hosting/)/[free if self-hosted](https://weblate.org/en/hosting/)

I prefer Crowdin as it has the best UI of the three and it is used by, among others, Mojang itself. At the same time, I understand that Mojang using it may be a drawback, so other options are fine too.

### Reasoning

- Easier collaboration on translation strings
- Strings can be commented
- Users get locale update notifications
- All strings don't have to be translated on one go 
- String updates create an automatic pull request
- etc.

**Comment by Secret-chest** [comment]
They all suck. Someone votes "good enough" strings and forgets, then you have no chance to make a better one. That's why I use a custom resource pack to translate Minecraft to Romanian.

**Comment by Madis0** [comment]
> They all suck. Someone votes "good enough" strings and forgets, then you have no chance to make a better one. That's why I use a custom resource pack to translate Minecraft to Romanian.

I'm sorry you've had that experience, and in an older version of Minecraft, I can relate as well. 

There are ways to solve it, though:
- vote for the translations
- discuss with the original commenter
- discuss with the language proofreader
- discuss with a global proofreader/project owner

So as long as we'd make the existing language contributors proofreaders, they'd get to choose which new strings get approved.

**Comment by andrii-bodnar** [comment]
Will be happy to assist with the Crowdin integration 🙂

**Comment by Aizistral** [comment]
> So as long as we'd make the existing language contributors proofreaders, they'd get to choose which new strings get approved.

Well yeah, here's the issue - too many people just drop in the translation once and then disappear. Overall I do not think translation platform is something we absolutely need at this point, not until we have more recurrent localizators.
