### ISSUE TITLE
status_insecure_whitelist_all_servers string is missing

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#267]
### Modloader

Fabric

### Minecraft Version

22w44a

### Modloader Version

Fabric Loader 0.14.10, bundled FAPI

### No Chat Reports Version

22w44a-1.14.0

### Bug Description

Translation string `gui.nochatreport.status_insecure_whitelist_all_servers` is missing. Would PR but I'm not sure what exactly it should say.

### Steps to Reproduce

1. Enable "whitelist all servers" setting
2. Join a server
3. Hover at the status icon

**Comment by Aizistral** [comment]
It's not needed any longer, I just forgot to actually remove it in the code.
