### ISSUE TITLE
Don't keep assumptions for whitelisted servers

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#268]
### Modloader

Fabric

### Minecraft Version

22w44a

### Modloader Version

Fabric Loader 0.14.10, bundled FAPI

### No Chat Reports Version

22w44a-1.14.0

### Bug Description

"Whitelist all servers" doesn't seem to behave the same as it did on 1.19.1-1.19.2. On those versions it simply avoided the warning screen while still determining the status of the server and opting out from signing where possible. 

Now it seems to opt into signing on all servers, which is pointless as the user might as well toggle the option "enable mod" for a better effect.

### Steps to Reproduce

1. Enable "whitelist all servers"
2. Join a server
3. Look at the server status icon

**Comment by Aizistral** [comment]
How do you suggest it should work?

**Comment by Madis0** [comment]
I want an option that would simply disable the full-screen warning on all servers and automatically give the signature when the server requires it, but not otherwise.

**Comment by Aizistral** [comment]
This isn't really an unintended behavior, and for the time being it will remain the way it is. I will return to this with implementation of signing modes (in particular #253).
