### ISSUE TITLE
Does this mod conflict with the no telemetry mod?

### ISSUE THREAD

**Issue by vittogialli** [Aizistral-Studios/No-Chat-Reports#27]
By this I mean if I can use them both, if i need to remove the no telemetry one and how the implementation is done (is it just copy pasted from the other mod? is it a rewrite? is there any difference on how much it's blocked?)

**Comment by Daxanius** [comment]
You don't need to use them both, this one has an anti telemetry measure implemented.

View the implementation [here](https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.X-Forge/src/main/java/com/aizistral/nochatreports/mixins/MixinClientTelemetryManager.java)

**Comment by Aizistral** [comment]
Yeah, you don't need both. But they shouldn't conflict if you install both, so you can include both in modpack if you want to support that mod as well, for instance.

My implementation, which @Daxanius kindly referenced above, is a bit different from [what No Telemetry does](https://github.com/kb-1000/no-telemetry/tree/main/src/main/java/de/kb1000/notelemetry/mixin), but it ultimately achieves the same thing - none of the data it tries to collect by default is sent anywhere.
