### ISSUE TITLE
Vanilla clients are kicked when sending messages on server with NCR installed

### ISSUE THREAD

**Issue by Aizistral** [Aizistral-Studios/No-Chat-Reports#271]
### Modloader

Fabric

### Minecraft Version

22w44a

### Modloader Version

Fabric Loader 0.14.10, bundled Fabric API.

### No Chat Reports Version

22w44a-v1.14.2

### Bug Description

Vanilla clients are kicked with "Received chat packet with missing or invalid signature" when sending messages on server with No Chat Reports installed.

### Steps to Reproduce

1. Start Fabric server with No Chat Reports installed;
2. Join from vanilla client;
3. Type something into the chat;
4. Behold!

**Comment by undnull** [comment]
The issue seems to emerge again when I updated the mod from %god_knows_what_version_for_1.19.2% to the latest version for 1.19.3 (v2.0.0)

**Comment by untodesu** [comment]
The exact reverse happens after I updated my client to 1.19.3: a vanilla server (paper though) kicks _me_ even with NCR set to _always sign messages_
