### ISSUE TITLE
No Chat Reports couldn't evaluate the safety of this server

### ISSUE THREAD

**Issue by stantios** [Aizistral-Studios/No-Chat-Reports#278]
### Modloader

Quilt

### Minecraft Version

1.19.2

### Modloader Version

Quilt: 0.17.6

### No Chat Reports Version

1.19.2-v1.13.11

### Modpack Info

Fabulously Optimized - https://modrinth.com/modpack/fabulously-optimized

### The latest.log File

https://mclo.gs/FcXj7B9 - Ignore the lines that are realated to chunks, it's an issue with a different mod.

### Bug Description

I was told to report this issue if this happened, the server has No Chat Reports as well: 
![image](https://user-images.githubusercontent.com/98621617/200180735-2666abb2-a015-414d-95b6-6429330e31db.png)

**Comment by Madis0** [comment]
Could you reproduce this with only Multiconnect (and any dependencies) on Quilt and Fabric? I think that mod is the issue.

**Comment by Aizistral** [comment]
I think this might be somehow related to #132. Does server in question run on Fabric?

**Comment by stantios** [comment]
> I think this might be somehow related to #132. Does server in question run on Fabric?

Yes, the server runs on Fabric. Also I can join the server, it's just I keep getting that message.

**Comment by stantios** [comment]
> Could you reproduce this with only Multiconnect (and any dependencies) on Quilt and Fabric? I think that mod is the issue.

I don't have or use the mod 'multiconnect' since it's not compatible with Quilt.

**Comment by Madis0** [comment]
Ah, it wasn't the mod itself, it was its API (ln 72 in your logs):
> MultiConnect API

**Comment by stantios** [comment]
> Ah, it wasn't the mod itself, it was its API (ln 72 in your logs):
> 
> > MultiConnect API

Oh ok

**Comment by stantios** [comment]
Closed as I don't get the issue anymore with the server.
