### ISSUE TITLE
(Discussion) What if Cryptographic signatures were forced by the game?

### ISSUE THREAD

**Issue by SB2DD** [Aizistral-Studios/No-Chat-Reports#28]
(This is not an issue, but rather a discussion. I know normally there should a Discussions tab, but it's disabled ig)
Anyways, I'm just worried that, with newer versions after 1.19.1, Mojang might try to fix this mod by forcing crypto-signing messaging **client-side**. Therefore, this mod would be quite irrelevant for compatibility with vanilla clients. Maybe this is an issue to prepare for. I guess adding a feature to send SYSTEM messages would be nice to be worked on??? Heck idk, but this is a fear I'm having and this mod seems to be the most popular to disable Mojang Reporting, sooo.. yeah. Could be nice to hear your thoughts now rather than when chaos would ensue.

(This is highly hypothetical and I'm looking way too much in the future, but forcing message signing could be the easiest way for Mojang to kill this mod)

**Comment by Aizistral** [comment]
> forcing crypto-signing messaging client-side

You mean that what Only Show Secure Chat does would be enabled at all times? The mod already has a way to counteract that in the form of converting player messages to system messages. For now it's default-off, but as of 1.19.1 it will be default-on.

**Comment by SB2DD** [comment]
Oh okay, I just found it through the code, sorry. Well, issue closed then, thanks!
