### ISSUE TITLE
Explain flow of keys, where everything is and how it operates.

### ISSUE THREAD

**Issue by maxsupermanhd** [Aizistral-Studios/No-Chat-Reports#3]
Hello, can someone explain somewhere how messages are signed and transferred between client, server, other clients and a report server. I would really appreciate if details would be out on curseforge page too.

Mainly I don't understand how chat signatures work. Does client generate private key for each session and uses it to sign all messages or will it send message to auth/session server for signing? Also what is being delivered to server that is handling reports?

**Comment by Aizistral** [comment]
I am right now in the process of making a video that will explain how signatures work. Stay tuned!

**Comment by Aizistral** [comment]
Done! You can watch it here: https://www.youtube.com/watch?v=hYAUEMlugyw
Now it is also referenced in description both CurseForge and Modrinth.
