### ISSUE TITLE
Chat icons

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#30]
To go along with #4, I suggest the following warning icons. These should be displayed in the rightmost edge of the chat textbox, to prevent being too intrusive.

* Green ✅
  * The mod has been discovered on the server
  * The server is using 1.18.2 or below
  * No detected reportable messages (so using different channel)
* Yellow ℹ️ 
   * The mod is working client-side only
* Red ⚠️ 
   * Player overrid the warning of #4 and messages are reportable

**Comment by ghost** [comment]
these should be displayed in the config menu when on  a server

**Comment by Aizistral** [comment]
> these should be displayed in the config menu when on a server

Nope, the mod doesn't support any kind of config menu right now.
I'll go with original suggestion.

**Comment by ghost** [comment]
> > these should be displayed in the config menu when on a server
> 
> Nope, the mod doesn't support any kind of config menu right now. I'll go with original suggestion.

Well then it should go into the pause menu! It would still be too invasive for the chatbox, unless the messages are reportable

**Comment by Madis0** [comment]
To be clear, I did only mean the box where you write your messages/commands in, not the individual messages themselves. So just one icon in the corner of the screen, while user is typing anyway.

**Comment by Aizistral** [comment]
So far my implementation looks like this
![image](https://user-images.githubusercontent.com/47505981/176864520-40a0096f-19df-4907-8a1c-bfa8fce6aa87.png)

**Comment by Madis0** [comment]
Looks great, except that last tooltip is a bit too complex. Try shortening the sentences a bit to make the message clearer.

**Comment by ghost** [comment]
these indicators must be able to be disabled

**Comment by Aizistral** [comment]
> these indicators must be able to be disabled

There will be a config option for that.

**Comment by Aizistral** [comment]
Was added in 1.19.1-pre2-v1.3.0.
