### ISSUE TITLE
ModMenu config broken

### ISSUE THREAD

**Issue by BuggyAl** [Aizistral-Studios/No-Chat-Reports#309]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

Fabric Loader 0.14.10 / API 0.68.0

### No Chat Reports Version

1.19.2-v1.13.12

### The latest.log File

https://mclo.gs/hBZKaNC

### Bug Description

NoChatReports config button does not appear in ModMenu mod list
![image](https://user-images.githubusercontent.com/64368488/205463566-23630d96-e210-4798-997d-07f122eb43e5.png)

### Other Information

Mod Menu 4.1.1

**Comment by Madis0** [comment]
You probably just haven't downloaded [Cloth Config](https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3972372).

**Comment by BuggyAl** [comment]
tyvm :)
