### ISSUE TITLE
Out of order chat packages

### ISSUE THREAD

**Issue by VolkerSchlegel** [Aizistral-Studios/No-Chat-Reports#313]
### Modloader

Fabric

### Minecraft Version

1.19.2

### Modloader Version

Fabric API 0.61.0+1.19.2 Fabric 0.14.9

### No Chat Reports Version

1.19.2-v1.13.12

### Modpack Info

https://modrinth.com/modpack/fabulously-optimized

### The latest.log File

https://mclo.gs/7Rh0zJ0

### Bug Description

I sometimes get kicked for out-of-order chat packages when using commands. It happens randomly, even if I don't send any other commands or chat messages in that time.

### Other Information

I also added litematica to the modpack, but that shouldn't be causing the bug. The bug doesn't happen without No Chat Reports.

**Comment by Aizistral** [comment]
What server are you encountering this on? I'm asking since from the logs it seems like there's some kind of proxy involved, and proxies have other known issues (see #247).

**Comment by Madis0** [comment]
Seems to be `mc.novylen.net` according to 
> [10:10:17] [Render thread/INFO]: [CHAT] welcome to mc.novylen.net, you're in the lobby

**Comment by VolkerSchlegel** [comment]
It's `mc.novylen.net`, I don't know whether it also happens on other servers, I haven't played on any other server for the last few months.

**Comment by Madis0** [comment]
The server says it is on 1.19.3 now, so perhaps that helped.

**Comment by VolkerSchlegel** [comment]
Seems to be fixed now, will reopen if it happens again
