### ISSUE TITLE
Let players can decrypt with more keys

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Aizistral-Studios/No-Chat-Reports#319]
### Idea

I want to let players can set more than 1 keys to decrypt the message, now they can see messages encrypted by different keys if sender use different keys.

### Reasoning

My friends use different keys.

**Comment by Madis0** [comment]
How would encrypting work then?

**Comment by IlyaTheSawmill** [comment]
You can set more keys in the encryption config, and decrypt all messages with the keys you have set.

**Comment by Madis0** [comment]
That's how decryption would work. 

But encryption? Should there be some kind of drop-down for selecting the key to encrypt with?

**Comment by IlyaTheSawmill** [comment]
You can select 1 key to encrypt.

**Comment by Aizistral** [comment]
Duplicate of #245.
