### ISSUE TITLE
Don't disable the telemetry data toggle when disableTelemetry is true

### ISSUE THREAD

**Issue by ghost** [Aizistral-Studios/No-Chat-Reports#320]
### Idea

You should let the user check their telemetry settings from None to Minimal or All.

### Reasoning

As mojang is being way more transparent with telemetry now than they were before and have added the in game gui for it.

**Comment by Madis0** [comment]
IIRC button disabling is a vanilla behaviour when that "none" setting is forced. 

But if NCR did what you suggested, it'd have to mixin and rework the whole toggle button (instead of just forcing the telemetry value). Whether that is a good thing is up to Aizistral.

**Comment by Aizistral** [comment]
Won't be implemented because it would be difficult and prone to compatibility issues. I think I will go with #326 instead and simply remove telemetry button entirely if NCR is configured to prevent telemetry, as it would not be relevant anyways.
