### ISSUE TITLE
Remove the Telemetry Data Button

### ISSUE THREAD

**Issue by ghost** [Aizistral-Studios/No-Chat-Reports#322]
### Idea

The Telemetry Button should be removed. It is not in use and serves no purpose with the mod installed.

### Reasoning

The addition of the Telemetry Data button adds a new row for buttons on the menu. This shifts the placement of the Done button and can mess with players who are used to the positioning in 1.19.2 and below.

### Other Information

Modloader
Fabric

Minecraft Version
1.19.3

Modloader Version
Fabric Loader 0.61.3

No Chat Reports Version
1.19.3

**Comment by Madis0** [comment]
Removing the button would conflict with the idea of #320, might mess with other mods' expectations (of where vanilla buttons are located) and the button currently shows the player, what the telemetry toggle actually protects users against. I do not support this idea.

(edited as I misunderstood the OP initially)

**Comment by ghost** [comment]
The Telemetry Data button is useless, and there is no reason in my eyes not to remove it. Having a toggle in the NCR config if you want to have it or not is the easiest solution.

**Comment by ghost** [comment]
Reopened as a chain issue with #154. See #326
