### ISSUE TITLE
Irrelevant tooltip lines should not be visible on ✅ 

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#323]
### Modloader

Fabric

### Minecraft Version

1.19.3

### Modloader Version

Fabric Loader: 0.14.11, API 0.68.1+1.19.3

### No Chat Reports Version

1.19.3-v.1.18.0

### Bug Description

These lines should not be visible on ✅  because modes cannot be cycled and the selected signing mode is 
irrelevant there anyway as the server enforces it.

![image](https://user-images.githubusercontent.com/8611110/206540206-d151a8a9-39ac-4656-a8de-abfdc463a1b0.png)

(On-Demand was set by me on config)

### Steps to Reproduce

1. Go to a singleplayer world
2. Open chat and hover on ✅ 
3. See the tooltip
4. Try to click to toggle states
5. Nothing happens

**Comment by Aizistral** [comment]
They are displayed for consistency reasons, and in fact it is possible to sign your messages on secure servers if you select "Always" as mode. This is intentionally implemented that way to allow some kind of workaround for servers that might try to abuse secure status to advertise themselves as secure but then demand signed messages anyways.

**Comment by Madis0** [comment]
But the mode cycling itself does not work on secure servers - that's a separate bug?

**Comment by Aizistral** [comment]
> But the mode cycling itself does not work on secure servers - that's a separate bug?

It is uncyclable in 2 cases:
1. You are logged in from offline account;
2. You are in a singleplayer world, as then there simply is no server address to associate the setting with.

I agree it might be a good idea to remove these lines in case of singleplayer, but that would be a different issue as enchancement, not a bug.
