### ISSUE TITLE
Safety message indicators still show in Singleplayer

### ISSUE THREAD

**Issue by ghost** [Aizistral-Studios/No-Chat-Reports#325]
### Modloader

Fabric

### Minecraft Version

1.19.3

### Modloader Version

Fabric Loader 0.63.1 + Fabric API 0.68.1+1.19.3

### No Chat Reports Version

1.19.3-v1.18.0 

### Bug Description

Whenever playing on a singleplayer world, your chat messages and system chat messages still have a gray safety indicator. I have all of the hide indicator options on in the config.

A screenshot is shown below showcasing this issue.

![bug](https://user-images.githubusercontent.com/19875208/206586072-0ee624a8-60fd-4359-9649-4d78a0b8e863.png)

Keep in mind that if I open a LAN world this issue does **not** occur.

**Comment by ghost** [comment]
This is my config file. 

[Config File](https://pastebin.com/raw/yuHBTwaX)

**Comment by DreamStanMan** [comment]
This is still an issue.
