### ISSUE TITLE
Remove the Player Reporting and Telemetry Data Buttons

### ISSUE THREAD

**Issue by ghost** [Aizistral-Studios/No-Chat-Reports#326]
### Idea

You should make it an option to remove the Player Reporting and Telemetry Data Buttons in the config.

### Reasoning

The Player Reporting and Telemetry Data Buttons serve no purpose with the mod installed, and should be removed, or at least a toggle in the config. 

The addition of the Telemetry Data button adds a new row for buttons on the menu. This shifts the placement of the Done button and can mess with players who are used to the positioning in 1.19.2 and below.

### Other Information

This is possible. There is a mod that does this but it isn't supported anymore. https://modrinth.com/mod/nrb

**Comment by Madis0** [comment]
Player Reporting has its use of showing the Social Interactions view though, which was previously very much hidden. And from there players can hide others' messages or block them on Xbox.

**Comment by ghost** [comment]
Well, you should be able to have a toggle in the config for the people that don't want it there, such as myself. The Social Interactions screen can still be opened by pressing P.

**Comment by Aizistral** [comment]
I would rather have #322 and #154 separately as they are different concerns. Will close this and reopen those two.
