### ISSUE TITLE
Posible reporting/ban from earlier versions of Minecraft

### ISSUE THREAD

**Issue by saavor** [Aizistral-Studios/No-Chat-Reports#33]
Mojang has mentioned that you could also be banned from past versions of the game. I'm not sure if this means from in-game or literally just preventing the launcher from running that version but either way it seems like something they're going to be doing at some point.
<img width="744" alt="Screen Shot 2022-06-30 at 6 29 53 PM" src="https://user-images.githubusercontent.com/29069199/176789297-e3a74928-3059-456f-b582-7ac422c8ebeb.png">
Perhaps in the future, a port to earlier versions might be required. I'm just creating this issue to alert of this potential problem.

**Comment by bluebear94** [comment]
The reporting system only works for versions from 1.19 on (only 1.19.1 and later have the report screen, but even 1.19 has signed chat messages).

The banning is done on the authentication service by refusing to authenticate the player, and there’s nothing this mod can do about that.

**Comment by Aizistral** [comment]
> The banning is done on the authentication service by refusing to authenticate the player, and there’s nothing this mod can do about that.

Not that there is nothing it can do, but the scale of what needs to be done to work around this is beyond the scope of this project. For now I am focusing on providing community with means to prevent bans before they happen, and luckily - only versions that have signed messages in them need to be covered by this.
