### ISSUE TITLE
1.19.3 forge suport ? 

### ISSUE THREAD

**Issue by comonier** [Aizistral-Studios/No-Chat-Reports#331]
1.19.3 forge suport ? ty

**Comment by Madis0** [comment]
> Forge update will be lagging behind a bit since there's a high chance of having some bugs early on, and I would rather deal with them on Fabric then have to cross-commit across two branches

https://discord.com/channels/757941072449241128/992979156767883375/1050506567168036965

**Comment by Aizistral** [comment]
Done.
