### ISSUE TITLE
Servers that `preventsChatReports` may not prevent chat reports at all

### ISSUE THREAD

**Issue by teddyxlandlee** [Aizistral-Studios/No-Chat-Reports#332]
### Idea

See: https://github.com/Aizistral-Studios/No-Chat-Reports/wiki/How-to-Get-Safe-Server-Status#add-query-data

Without verification, NCR 100% trust a server which sets `preventsChatReports` to true.

What if the server does nothing but setting the property to true? This leads players into danger.

I'm wondering if there is a way to verify its reliability.

**Comment by Aizistral** [comment]
Mod is already designed with awareness of this fact:

- NCR will prevent the client from sending signed messages to the server by default, and if server suddenly demands messages to be signed despite advertising itself as secure then mod will stop displaying its status as secure;
- If NCR detects any signed messages in the chat then it will also stop displaying it as secure.

Taking that into account - there is very little damage that server can do to NCR user by falsely claiming secure status. Further measures against this are in consideration, in particular something similar to #296 but specifically oriented at preventing NCR from taking server's word for its security when it is known to be untrue might be worth implementing.
