### ISSUE TITLE
Overlay conflict between Better Compatibility Checker and No Chat Reports

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Aizistral-Studios/No-Chat-Reports#343]
### Modloader

Forge

### Minecraft Version

1.19.2

### Modloader Version

Forge 43.2.0

### No Chat Reports Version

1.19.2-v1.5.1

### Modpack Info

https://www.curseforge.com/minecraft/modpacks/create-on-a-potato-pc-sky/files/4288014

### Bug Description

On the server page, both Better Compatibility Checker and No Chat Reports occupy the same space and it is especially difficult to hover over the correct pixel to view the Better Compatibility Checker info
![image](https://user-images.githubusercontent.com/17887664/210420978-308bdef6-6ff2-47db-89d2-05954118c42c.png)
![image](https://user-images.githubusercontent.com/17887664/210420995-205d218c-b48a-44af-bf61-b525d58f8d92.png)

### Other Information

I have also posted the on the Better Compatibility Checker github
https://github.com/nanite/BetterCompatibilityChecker/issues/16

**Comment by Aizistral** [comment]
You can adjust the position of verified icon via No Chat Reports' client config to address this in your modpack or whatever, speficially `verifiedIconOffsetX` and `verifiedIconOffsetY` options.

**Comment by ClaudiusMinimus** [comment]
Thank you!
![image](https://user-images.githubusercontent.com/17887664/210820374-019040d1-e265-436b-a9e6-37f356938009.png)
