### ISSUE TITLE
Safe Server ICON Position Change

### ISSUE THREAD

**Issue by itsdinkd** [Aizistral-Studios/No-Chat-Reports#357]
### Idea

Create config option to move the icon for safe server (and unsafe I imagine) as it conflicts with other mods.

![image](https://user-images.githubusercontent.com/35115304/216218826-258c5a15-7ae3-4a69-b1b5-cb2054ea1e1b.png)

The icon behind it in question is "BCC" Better Check Compatibility.

**Comment by Aizistral** [comment]
See #343.
