### ISSUE TITLE
In-game config is not available

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Aizistral-Studios/No-Chat-Reports#360]
### Modloader

Forge

### Minecraft Version

1.19.3

### Modloader Version

Forge 44.1.5

### No Chat Reports Version

1.19.3-v2.0.0

### Bug Description

The in-game config isn't available in Forge's built-in modmenu.
I entered the "Mod Option" screen and found the config button of NCR isn't available.
I have ModMenu mod installed.

### Steps to Reproduce

1. Open Forge's built-in modmenu.
2. Click NCR.
3. Found that in-game config of NCR isn't available.

**Comment by Aizistral** [comment]
This isn't supposed to work on Forge, as far as I know it doesn't have any Cloth Config API integration out of the box, which is something Fabric's ModMenu interoperates with. So this isn't really a bug. In principle it is possible to manually add some kind of similar config button there, but suggestion issue would be more suited if that's what you wanted to propose.
