### ISSUE TITLE
Wrong shortcut on macOS for temporaily disabling encryption

### ISSUE THREAD

**Issue by JacksonChen666** [Aizistral-Studios/No-Chat-Reports#361]
### Modloader

Fabric

### Minecraft Version

1.19.3

### Modloader Version

Fabric: 0.14.13, API: 0.73.2+1.19.3

### No Chat Reports Version

1.19.3-v2.0.0

### Bug Description

The encryption hover dialog tells the user to hold Ctrl (control) to temporarily disable encryption.
However, only Cmd (command) can temporarily disable encryption.

### Other Information

<img width="547" alt="" src="https://user-images.githubusercontent.com/50755746/216788904-e7136dca-f719-4344-93c4-9d563d308cef.png">

**Comment by MacchuPicchu3** [comment]
Here to add that since the default Copy/Paste shortcuts for Mac are Command-C and Command-V, respectively, this bug interferes with players' ability to interact with chat normally.

**Comment by Madis0** [comment]
> Here to add that since the default Copy/Paste shortcuts for Mac are Command-C and Command-V, respectively, this bug interferes with players' ability to interact with chat normally.

In that case I suggest to fix the issue by actually enforcing _Ctrl_ use for this on Macs, keeping the tooltip unchanged as well. Should be an easy if-check.

**Comment by Aizistral** [comment]
> Here to add that since the default Copy/Paste shortcuts for Mac are Command-C and Command-V, respectively, this bug interferes with players' ability to interact with chat normally.

I don't see how it interferes more than, say, on Windows. It only matters whether they key is held down at the moment the message is sent, copying or pasting something before that moment doesn't affect anything.
