### ISSUE TITLE
Suggestion: Bypassing mojangs server block list

### ISSUE THREAD

**Issue by uriesk** [Aizistral-Studios/No-Chat-Reports#366]
### Idea

Mojang has a public banlist for server IPs and server URLs that is enforced by the client.
Make it possible to ignore that list and still join those banned servers (maybe with an extra prompt asking if you really want it).

### Reasoning

Fits to the theme of the mod and is jet another mojang "feature" to police players on private servers.

### Other Information

Mojang launched a recent banwave and the reasons included plugins for "alcohol" and "guns".

**Comment by Aizistral** [comment]
Despite this being quite easy to implement, I don't think this is something I'd want to include in NCR. Mojang typically ban servers for EULA violations; implementing a workaround might put this mod in jeopardy as being viewed as assisting those violations. I do not believe Mojang themselves will take any action against it, but CurseForge/Modrinth very well can, and they did in the past against mods that tried to implement similar features.
