### ISSUE TITLE
"You can always chat safely in singleplayer" appears on LAN

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#372]
### Modloader

Fabric

### Minecraft Version

1.19.4

### Modloader Version

Fabric Loader 0.14.17, API 0.76.0

### No Chat Reports Version

v1.19.4-v2.1.0

### Bug Description

"You can always chat safely in singleplayer" appears on LAN servers.

### Steps to Reproduce

1. Open a world in singleplayer
2. Open to LAN
3. Observe status tooltip above chatbox

### Other Information

Could use a separate tooltip or one that covers both. Also unsure how it appears when joining LAN servers hosted by others.

**Comment by Aizistral** [comment]
> Also unsure how it appears when joining LAN servers hosted by others.

It appears as unknown first, and unintrusive after sucessfully sending an unsigned message. I'll see later if it would be possible for NCR client to communicate its safety status to other clients when hosting a LAN world.

**Comment by Aizistral** [comment]
I changed the wording of this particular safety status to mention that self-hosted LAN servers are also safe, but the thing I mentioned above is still relevant. You can create a separate issue for that.
