### ISSUE TITLE
Chat Message Navigation

### ISSUE THREAD

**Issue by Lukebb04** [Aizistral-Studios/No-Chat-Reports#375]
### Modloader

Fabric

### Minecraft Version

1.19.4

### Modloader Version

Fabric: Loader 0.14.17 + API 0.76.0

### No Chat Reports Version

1.19.4-v2.1.0

### Bug Description

You can't navigate left or right in chat messages

### Steps to Reproduce

1. Type something into the chat
2. Press up arrow

**Comment by Madis0** [comment]
Your steps say you press up and description says you press left or right, which one is it then?

**Comment by LopyLuna** [comment]
I Have this Same issue 
Whenever I Open the chat & press up to repeat a message/command it will select the buttons also which make it where its impossible to put text in chat afterword's

**Comment by Madis0** [comment]
Ahh, I see
That's probably due to 1.19.4 accessibility stuff

**Comment by notaduck448** [comment]
Can confirm. Once you press the up arrow to cycle through messages, it automatically selects the encryption button which prevents you from typing in chat. The only way to fix is to close chat and reopen.

**Comment by Dory05** [comment]
I can likewise confirm that this occurs when you press up to load a previous chat message. It is then impossible to deselect the encryption button without closing out of chat entirely.

**Comment by TadaCZE** [comment]
Did you find a way to counteract it?

**Comment by Madis0** [comment]
Workaround: 
> Mods -> No Chat Reports -> (config) -> Show server safety -> No

**Comment by Parilia** [comment]
> Workaround:
> 
> > Mods -> No Chat Reports -> (config) -> Show server safety -> No

This does not seem to work, as pressing the up arrow selects the encryption button.
as shown here: https://ibb.co/jDNPkkR

**Comment by Madis0** [comment]
Ah yes, hide that too for the time being.

**Comment by Parilia** [comment]
which config is it ?

**Comment by razorchase49** [comment]
> which config is it ?

In the in-game config, disable "Show encryption button" and "Show server safety"

**Comment by Parilia** [comment]
My ingame cofigs arent working for some reason but  found the config file

**Comment by razorchase49** [comment]
> My ingame cofigs arent working for some reason but found the config file

In that case, go to your config\NoChatReports folder, open NCR-Encryption.json, and set both showEncryptionButton and showEncryptionIndicators to false.

**Comment by Aizistral** [comment]
Sorry that I couldn't address this right away. I'll be trying to fix this today.

**Comment by ghost** [comment]
Yeah for me the annoyance is that pressing up arrow after "/" selects the encryption button which when i try to send the command gets pressed instead
