### ISSUE TITLE
Can't decrypt with EssentialsXChat plugin in some cases

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Aizistral-Studios/No-Chat-Reports#376]
### Modloader

Forge

### Minecraft Version

1.19.4

### Modloader Version

Forge 45.0.50

### No Chat Reports Version

1.19.4-2.1.1

### The latest.log File

Go to http://utcs.wdfiles.com/local--files/latest-log/latest.log to see.

The bug happened on line 525 to 529.

### Bug Description

I'm using a server that has EssentialsXChat installed, and use it to format chats. And then I found that encryption doesn't work--the scamble(encrypted message) was shown. I can't read decrypted messages.

**Comment by Madis0** [comment]
Screenshots? Logs?

**Comment by IlyaTheSawmill** [comment]
See http://utcs.wdfiles.com/latest-log/

**Comment by Aizistral** [comment]
I just tried to reproduce this on 1.19.4 Paper server with EssentialsX and EssentialsXChat 2.19.7, and encountered no issues with decryption.
Can you specify the version of your server and versions of EssentialsX/EssentialsXChat you are using? It would also help if you provided your chat format settings.

**Comment by IlyaTheSawmill** [comment]
The server is Leaves, and the plugin is 2.19.7.
Format:
[{WORLDNAME}]{DISPLAYNAME}：{MESSAGE}
Please take care: the colon is full-width(：)

**Comment by IlyaTheSawmill** [comment]
Perhaps it was caused by a full width colon?
The version of Leaves is latest.

**Comment by IlyaTheSawmill** [comment]
Now I can confirm that it is caused by the full-width characters. So can you fix it please?

**Comment by Aizistral** [comment]
I'll check this shortly

**Comment by Aizistral** [comment]
Reproduced successfully. No idea why full width colon is causing decryption to fail yet, but I'll figure it out.

**Comment by Aizistral** [comment]
Example of a jsonified message causing the issue, posting here for later use: `{"translate":"%s","with":[{"text":"[world]Aizistral:,'~=}{[12<:?#·©}]¬\"?2|;{2\">?"}]}`

**Comment by Aizistral** [comment]
I have made it compatible with full-width colon, but this really is just a band-aid fix for now. The actual issue stems from some of the assumptions that go into handling custom chat formats, namely that there will always be at least one space separating encrypted part from the rest of the message. I'll see what I can do about that in 1.20.
