### ISSUE TITLE
Arrow key navigation with No Chat Reports buttons prevents sending chat/commands from chat history

### ISSUE THREAD

**Issue by Evtema3** [Aizistral-Studios/No-Chat-Reports#379]
### Modloader

Fabric

### Minecraft Version

1.19.4

### Modloader Version

Fabric: Loader 0.14.17 + API 0.76.0

### No Chat Reports Version

1.19.4-v2.1.0

### Bug Description

While chat is open, trying to go back to previous chat/commands from chat history by pressing the up arrow key highlights the No Chat Reports "Encryption" lock button. Once the button is highlighted, pressing Enter to send the current chat/command instead performs the click action for the button, and no chat/command is sent. This also happens when the right arrow key is used after the up arrow key to highlight the "You can always chat safely in singleplayer" button in applicable scenarios. Using the down arrow key does not de-highlight these buttons, and the only way to send chat again is by hitting ESC and reopening the chat window.

### Other Information

Below is my list of mods, output in client logs while booting up my 1.19.4 Fabric profile:

Loading 73 mods:
	- carpet 1.4.101+v230319
	- dynamicfps 2.2.0
	   \-- com_moandjiezana_toml_toml4j 0.7.2
	- fabric-api 0.76.0+1.19.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-api-lookup-api-v1 1.6.24+49abcf7ef4
	   |-- fabric-biome-api-v1 13.0.6+348a9c64f4
	   |-- fabric-block-api-v1 1.0.5+e022e5d1f4
	   |-- fabric-blockrenderlayer-v1 1.1.33+c2e6f674f4
	   |-- fabric-client-tags-api-v1 1.0.14+1134c5b8f4
	   |-- fabric-command-api-v1 1.2.25+f71b366ff4
	   |-- fabric-command-api-v2 2.2.4+ae0966baf4
	   |-- fabric-commands-v0 0.2.42+df3654b3f4
	   |-- fabric-containers-v0 0.1.52+df3654b3f4
	   |-- fabric-content-registries-v0 3.5.7+ae0966baf4
	   |-- fabric-convention-tags-v1 1.4.0+9a7c5daaf4
	   |-- fabric-crash-report-info-v1 0.2.14+aeb40ebef4
	   |-- fabric-data-generation-api-v1 11.3.5+5da15ca1f4
	   |-- fabric-dimensions-v1 2.1.44+7f87f8faf4
	   |-- fabric-entity-events-v1 1.5.12+e45f7c65f4
	   |-- fabric-events-interaction-v0 0.4.42+a1ccd7bff4
	   |-- fabric-events-lifecycle-v0 0.2.51+df3654b3f4
	   |-- fabric-game-rule-api-v1 1.0.32+a1ccd7bff4
	   |-- fabric-item-api-v1 2.1.16+09a3510cf4
	   |-- fabric-item-group-api-v1 3.0.3+043f9acff4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-keybindings-v0 0.2.30+df3654b3f4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-loot-api-v2 1.1.25+75e98211f4
	   |-- fabric-loot-tables-v1 1.1.29+9e7660c6f4
	   |-- fabric-message-api-v1 5.1.0+1ee8be40f4
	   |-- fabric-mining-level-api-v1 2.1.37+49abcf7ef4
	   |-- fabric-models-v0 0.3.29+11ba9c3bf4
	   |-- fabric-networking-api-v1 1.2.22+ca5f59aaf4
	   |-- fabric-networking-v0 0.3.39+df3654b3f4
	   |-- fabric-object-builder-api-v1 7.0.1+63b515f4f4
	   |-- fabric-particles-v1 1.0.22+f1e4495bf4
	   |-- fabric-recipe-api-v1 1.0.6+a1ccd7bff4
	   |-- fabric-registry-sync-v0 2.1.2+a383ab97f4
	   |-- fabric-renderer-api-v1 2.2.4+81e8c576f4
	   |-- fabric-renderer-indigo 1.1.0+81e8c576f4
	   |-- fabric-renderer-registries-v1 3.2.37+df3654b3f4
	   |-- fabric-rendering-data-attachment-v1 0.3.27+afca2f3ef4
	   |-- fabric-rendering-fluids-v1 3.0.20+f1e4495bf4
	   |-- fabric-rendering-v0 1.1.40+df3654b3f4
	   |-- fabric-rendering-v1 2.1.0+8f878217f4
	   |-- fabric-resource-conditions-api-v1 2.3.0+e6c7d4eef4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   |-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	   |-- fabric-screen-handler-api-v1 1.3.18+5da15ca1f4
	   |-- fabric-sound-api-v1 1.0.8+75e98211f4
	   |-- fabric-transfer-api-v1 3.0.1+9003cbe9f4
	   \-- fabric-transitive-access-wideners-v1 3.0.2+63b515f4f4
	- fabricloader 0.14.17
	- indium 1.0.15+mc1.19.4
	- iris 1.5.2
	   |-- io_github_douira_glsl-transformer 2.0.0-pre9
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- languagereload 1.5.5+1.19.4
	- lithium 0.11.1
	- logical_zoom 0.0.19
	- minecraft 1.19.4
	- modmenu 6.1.0-rc.4
	   |-- fabric-api-base 0.4.23+9ff28bcef4
	   |-- fabric-key-binding-api-v1 1.0.32+c477957ef4
	   |-- fabric-lifecycle-events-v1 2.2.14+5da15ca1f4
	   |-- fabric-resource-loader-v0 0.11.0+938a1d56f4
	   \-- fabric-screen-api-v1 1.0.44+8c25edb4f4
	- nochatreports 1.19.4-v2.1.0
	- reeses-sodium-options 1.5.0+mc1.19.4-build.72
	- smoothboot 1.19.4-1.7.0
	- sodium 0.4.10+build.24
	- sodium-extra 0.4.18+mc1.19.4-build.100
	   |-- caffeineconfig 1.1.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- starlight 1.1.1+fabric.ae22326

**Comment by Evtema3** [comment]
An additional consequence is that no other key inputs are registered while the buttons are highlighted, so you can't even type a new chat message or use CTRL+A to copy the previous one unless you exit the chat window as a whole.

**Comment by Lukebb04** [comment]
This is open at #375

**Comment by Evtema3** [comment]
Ah, apologies. Thanks!
