### ISSUE TITLE
Consistent Crash on Startup, cross version, Fabric

### ISSUE THREAD

**Issue by mintyCATy** [Aizistral-Studios/No-Chat-Reports#383]
Minecraft consistently crashes with exit code -1 before initialization when launched with the mod. 
Consistent across 1.19.2 and 1.19.4, mod and Fabric version and API up to date.

![image](https://user-images.githubusercontent.com/128926711/227733429-7f91961c-141a-4c89-a1ff-207577d192b7.png)

[crash-2023-03-25_13.40.26-client.txt](https://github.com/Aizistral-Studios/No-Chat-Reports/files/11069737/crash-2023-03-25_13.40.26-client.txt)

**Comment by Madis0** [comment]
Something's wrong with your config. Try deleting `NoChatReports` folder from `.minecraft/config`.

**Comment by mintyCATy** [comment]
> Try deleting NoChatReports folder from .minecraft/config.

Fixed, thanks!
