### ISSUE TITLE
Mod does not respect FreedomChat.

### ISSUE THREAD

**Issue by MagmaSlime123** [Aizistral-Studios/No-Chat-Reports#402]
### Modloader

All loaders.

### Minecraft Version

1.19.4.

### Modloader Version

0.14.19.

### No Chat Reports Version

2.1.3.

### Modpack Info

N/A.

### The latest.log File

No logs related to this occur.

### Bug Description

Title.

### Steps to Reproduce

Use the mod and FreedomChat plugin.

![2023-05-24_23 54 57](https://github.com/Aizistral-Studios/No-Chat-Reports/assets/51277766/67208dc8-e73b-4d5f-bff9-43801f5a9f5e)

![image](https://github.com/Aizistral-Studios/No-Chat-Reports/assets/51277766/17daa061-c065-4a5a-a205-48f9e60d6bd3)

### Other Information

N/A.

**Comment by Madis0** [comment]
Since that message is from the server (only the visible text is changed by NCR), it is either an error with the plugin or the server setup, not NCR. [Did you read our tutorial?](https://github.com/Aizistral-Studios/No-Chat-Reports/wiki/Protecting-Server-Players)

**Comment by Aizistral** [comment]
So it was a server misconfiguration after all. Good to know for future reference.

**Comment by MagmaSlime123** [comment]
Apparently enforce-secure-profile must be off. NCR should know that its on and still allow sending unsigned messages. This wasn't an issue until recently.
