### ISSUE TITLE
Use markdown changelog

### ISSUE THREAD

**Issue by Aizistral** [Aizistral-Studios/No-Chat-Reports#409]
### Idea

Use Markdown for changelog file instead of HTML. 

### Reasoning

HTML was chosen only because it allowed to get more pretty-looking formatting on CurseForge, but it has some issues when updating already uploaded files, and doesn't look particularly good on Modrinth. Using Markdown would solve these issues and would make it easier to read changelog directly on GitHub.

**Comment by JustLetterV** [comment]
Would probably be better to include only new changes in the changelog when releasing a new version. Including changelogs for all past versions in the changelog of the new version doesn't really make sense and it kinda makes changelog pages useless.

**Comment by Aizistral** [comment]
> Would probably be better to include only new changes in the changelog when releasing a new version. Including changelogs for all past versions in the changelog of the new version doesn't really make sense and it kinda makes changelog pages useless.

Changelog pages are only present on Modrinth, at least so far. While this is a great feature and it alleviates the need to keep global changelog for Modrinth-exclusive projects, this project isn't one of those, and therefore it's not something we can really make use of.
