### ISSUE TITLE
Crash on Minecraft startup

### ISSUE THREAD

**Issue by KB-Q** [Aizistral-Studios/No-Chat-Reports#415]
### Modloader

Forge

### Minecraft Version

1.20.1

### Modloader Version

Forge 47.1.0

### No Chat Reports Version

1.20.1-v2.2.2

### Bug Description

Crash on startup:
https://paste.ee/p/YeQgi

**Comment by P3rf3ctXZer0** [comment]
Just so you know most if not all modders right now recommend this forge version Forge 47.1.3 and you are on Forge 47.1.0 some are also explicitly requiring it which means the game will crash on startup if you use any other version. Does it still crash when you use the required version?

**Comment by Madis0** [comment]
The crashlog has expired, no other details in the thread and the OP did not reply to the question, closing.
