### ISSUE TITLE
[1.20.1] Unable to load into previously created worlds, kicked with message "Invalid player data"

### ISSUE THREAD

**Issue by antibang** [Aizistral-Studios/No-Chat-Reports#419]
### Modloader

Forge

### Minecraft Version

1.20.1

### Modloader Version

Forge-47.1.43

### No Chat Reports Version

1.20.1-v2.2.2

### The latest.log File

https://mclo.gs/UnXyrYf

### Bug Description

When loading into any previously created world (all in 1.20.1), player is kicked with message "Invalid player data". It seems if I restart the game it *sometimes* will not kick me, but usually after loading into a world successfully once, I will be kicked regardless if I do not restart the game.

I've been updating my modpack into a new MC version, so I should mention I have quite a few mods on top of No Chat Reports. However, this **does not** seem to happen in a fresh install only with No Chat Reports, even with same configs transferred over. So, possibly a conflict?

### Steps to Reproduce

1. Create a new world and load in successfully
2. Exit world
3. Load back into the previously created world and be kicked with "Invalid player data"

**Comment by Madis0** [comment]
So are you able to load the world with same mods except NCR? Per logs, this looks more like an issue with ~~Vinery~~ other mods and I don't think it is related to NCR at all.

Edit: seems to be more like the randomtp mod

**Comment by antibang** [comment]
So sorry, I just tested and figured out it was Scaling Health. Only reason I submitted a report was I was told it was No Chat Reports by another dev on Discord.

Thanks for the help either way!
