### ISSUE TITLE
Warning loop for enforce-secure-profile=true

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#42]
Vanilla 1.19.1-pre2 server, modded Fabric client with NCR 1.3.0.

When trying to join the server, the #4 warning is displayed. However, when clicking "proceed" it appears again and again, only stopping when the user actually checks the checkbox first.

Edit: it even reappears once the player is kicked from the server, at which point the Proceed button gives a networking error :grin:

**Comment by Aizistral** [comment]
I think I encountered network error you have mentioned once during testing, but it seemed completely server-side, and I could not reproduce it. I hope it will be fixed in new build, but feel free to re-open this if you find out it still happens somehow.
