### ISSUE TITLE
Crash With NoChatReports

### ISSUE THREAD

**Issue by im-h** [Aizistral-Studios/No-Chat-Reports#420]
### Modloader

Fabric

### Minecraft Version

1.19.4

### Modloader Version

Fabric: Loader 0.14.21 + API 0.86.1

### No Chat Reports Version

1.19.4-v2.1.6

### The latest.log File

https://pastebin.com/3rD9KNCL

### Bug Description

Crashes even before the loading screen
Error Message: `The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'nochatreports'!`
Exit Code: `-1`

### Steps to Reproduce

Launch minecraft with the NoChatReports mod

### Other Information

Mods:
<sub><sub>3dskinlayers-fabric-1.5.3-mc1.19.4.jar
animatica-0.6+1.20.jar
appleskin-fabric-mc1.19.4-2.4.4.jar
architectury-8.2.89-fabric.jar
AxesAreWeapons-1.7.0-fabric-1.19.3.jar
balm-fabric-1.19.4-6.0.2.jar
bettermounthud-1.2.1.jar
BetterThirdPerson-Fabric-1.19-1.9.0.jar
capes-1.5.3+1.19.4-fabric.jar
cardinal-components-api-5.1.0.jar
charmofundying-fabric-6.3.0+1.19.4.jar
CITResewn-1.1.3+1.19.4.jar
clientcommands-2.7.13.jar
clienttweaks-fabric-1.19.4-10.0.2.jar
cloth-config-10.1.105-fabric.jar
complete-bone-meal-2.1.0+1.19.4.jar
completeconfig-2.3.1.jar
continuity-3.0.0-beta.3+1.19.4.jar
Controlling-fabric-1.19.4-11.1.5.jar
dcch-1.3.jar
DiagonalFences-v6.0.0-1.19.4-Fabric.jar
durabilitytooltip-1.1.4a-fabric-mc1.19.jar
dynamic-fps-2.2.0.jar
easiervillagertrading-1.19.3-fabric0.68.1-1.5.4.jar
EasyAnvils-v6.0.0-1.19.4-Fabric.jar
EasyMagic-v6.0.0-1.19.4-Fabric.jar
EasyShulkerBoxes-v6.0.0-1.19.4-Fabric.jar
eating-animation-1.9.3.jar
elytraslot-fabric-6.2.1+1.19.4.jar
entityculling-fabric-1.6.2-mc1.19.4.jar
entity_model_features_fabric_1.19.4-0.2.13.jar
entity_texture_features_fabric_1.19.4-4.4.4.jar
fabric-api-0.86.1+1.19.4.jar
fabric-carpet-1.19.4-1.4.101+v230319.jar
fabric-language-kotlin-1.10.8+kotlin.1.9.0.jar
fabric-release-regrowth-1.19.4-31.1.0.jar
fabrication-3.3.1+1.19.4.jar
FallingTree-1.19.4-3.12.2.jar
Female-Gender-Mod-fabric-1.19.4-3.0.1.jar
ferritecore-5.2.0-fabric.jar
figura-0.1.1+1.19.4.jar
fiveonefouroneeight-1.0.0.jar
ForgeConfigAPIPort-v6.0.2-1.19.4-Fabric.jar
indium-1.0.19+mc1.19.4.jar
interactic-0.2.0+1.19.4.jar
iris-mc1.19.4-1.6.4.jar
Jade-1.19.4-fabric-10.4.0.jar
jamlib-0.6.1+1.19.4.jar
jei-1.19.4-fabric-13.1.0.15.jar
journeymap-1.19.4-5.9.7-fabric.jar
JustEnoughResources-Fabric-1.19.4-1.3.3.221.jar
knowmyname-1.3.0.jar
krypton-0.2.2.jar
lambdynamiclights-2.3.1+1.19.4.jar
language-reload-1.5.8+1.19.4.jar
lazydfu-0.1.3.jar
LetSleepingDogsLie-1.19.3-4-1.1.1.jar
litematica-fabric-1.19.4-0.14.3.jar
lithium-fabric-mc1.19.4-0.11.1.jar
malilib-fabric-1.19.4-0.15.4.jar
microdurability-0.3.6+1.19.4.jar
midnightlib-fabric-1.3.0.jar
minihud-fabric-1.19.4-0.26.2.jar
mixintrace-1.1.1+1.17.jar
modelfix-1.10-fabric.jar
modmenu-6.3.1.jar
morechathistory-1.19.1-1.1.1.jar
MouseTweaks-fabric-mc1.19.4-2.24.jar
mousewheelie-1.11.1+mc1.19.4.jar
no-telemetry-1.7.0.jar
NoChatReports-FABRIC-1.19.4-v2.1.6.jar
notenoughanimations-fabric-1.6.4-mc1.19.4.jar
optigui-2.1.5.jar
owo-lib-0.10.6+1.19.4.jar
PerspectiveModRedux-1.17-0.0.5_01.jar
puzzle-1.5.0+1.19.4.jar
PuzzlesLib-v6.0.11-1.19.4-Fabric.jar
recursive-resources-2.4.3+1.19.4.jar
reeses_sodium_options-1.6.3+mc1.19.4-build.90.jar
right-click-harvest-3.2.2+1.19.x-1.20.1-fabric.jar
Searchables-fabric-1.19.4-1.0.3.jar
shulkerboxtooltip-fabric-3.4.0+1.19.4.jar
smoothboot-fabric-1.19.4-1.7.0.jar
sodium-extra-0.4.18+mc1.19.4-build.100.jar
sodium-fabric-mc1.19.4-0.4.10+build.24.jar
starlight-1.1.1+fabric.ae22326.jar
status-effect-bars-1.0.2.jar
supermartijn642configlib-1.1.7-fabric-mc1.19.jar
technomodel-1.0.4.jar
tooltipfix-1.1.1-1.19.3.jar
travelers-backpack-1.19.4-8.4.8.jar
trinkets-3.6.0.jar
tweakeroo-fabric-1.19.4-0.16.0.jar
VisualWorkbench-v6.0.1-1.19.4-Fabric.jar
waveycapes-fabric-1.4.0-mc1.19.3.jar
WI-Zoom-1.4-MC1.19.4.jar
yet-another-config-lib-fabric-3.1.0+1.19.4.jar</sub></sub>

**Comment by Madis0** [comment]
> [12:42:27] [Render thread/FATAL]: Could not read config file: C:\Users\Furya\AppData\Roaming\.minecraft\config\NoChatReports\NCR-Common.json

Delete the config file and let it regenerate
