### ISSUE TITLE
Disable the skin and ID reporting

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Aizistral-Studios/No-Chat-Reports#425]
### Idea

https://minecraft.fandom.com/wiki/Java_Edition_1.20.2

Is it possible to disable the skin and ID reporting?

### Reasoning

This is a F*CKING BAD content in Minecraft.

**Comment by Madis0** [comment]
Well, what exactly do you expect the mod to do against it, except hiding the button (for which the current toggle will still probably work)? 
You could just use a nickname or skin changer plugin on a server, or some cosmetics/custom skins/titles/pronouns mod on a client.

Banned usernames existed before as it is trivial to do it with a dictionary match, and some servers already banned people for offensive skins.

**Comment by IlyaTheSawmill** [comment]
Maybe you can disable it client-side, and make the server require all client install the same mod when join.

**Comment by Madis0** [comment]
Even then you must consider that usernames and skins are public data, which don't need signatures to verify. 
Therefore they can be reported through any server, [online](https://help.minecraft.net/hc/en-us/requests/new?ticket_form_id=4416074743565), or even without a report if they get caught in some dictionary match or some skin inspection by Mojang.

**Comment by IlyaTheSawmill** [comment]
Since this CANNOT make you get banned (this just tell you change your username or skin), and server admins also dislike offensive skins and IDs, this feature is not important.
