### ISSUE TITLE
when on server, disabled player name and skin report

### ISSUE THREAD

**Issue by hyplant** [Aizistral-Studios/No-Chat-Reports#426]
### Idea

希望在即将到来的1.20.2，这个模组安装在服务端时，可以阻止玩家举报用户名和皮肤。

In the upcoming 1.20.2 , if installed on the server, I hope to prevent players from reporting usernames and skins.

### Reasoning

根据更新日志，在用户可以举报一个玩家的用户名和皮肤。

According to the 23w33a changelog, now users can report a player's skin and username.

![Screenshot_20230818_201601](https://github.com/Aizistral-Studios/No-Chat-Reports/assets/86937725/13a0ea42-246f-4282-b662-7cef0c7e18ef)

### Other Information

直接阻止举报皮肤也许是困难的，但可以设计成：安装此模组时，在客户端禁止举报皮肤和用户名。当模组安装在服务端或客户端启动多人游戏时，该模组可以阻止未安装该模组的客户端加入。

It may be difficult to prevent reporting skins and ua
sernames directly, but it can be designed to prevent reporting skins and usernames on the client. When the mod is installed on the server or the client starts a multiplayer game, the mod can prevent players who haven't installed this mod on the client from joining.

**Comment by IlyaTheSawmill** [comment]
Duplicate with #425 (Closed as not planned by author (me))

**Comment by IlyaTheSawmill** [comment]
它也应该禁止举报“做了什么我不喜欢的事”。
It should also disable reporting "have done sth I don't like".

**Comment by Madis0** [comment]
> Even then you must consider that usernames and skins are public data, which don't need signatures to verify.
Therefore they can be reported through any server, [online](https://help.minecraft.net/hc/en-us/requests/new?ticket_form_id=4416074743565), or even without a report if they get caught in some dictionary match or some skin inspection by Mojang.

So you're better off installing some kind of skin changer/nickname mod to the server, rather than expecting NCR to guard against user reporting.

---

@IlyaIvanovsky 

> 它也应该禁止举报“做了什么我不喜欢的事”。 It should also disable reporting "have done sth I don't like".

That should be a separate issue

**Comment by IlyaTheSawmill** [comment]
> That should be a separate issue
OK, #427 then.

**Comment by Madis0** [comment]
> Just so that y'all know, I've no intent of creating a dedicated mod to counteract skin/name reporting or adding features to do so as part of NCR
> Don't see it as that big of a deal is all. Mojang have already been policing names and skins, and it doesn't feel like an overreach that chat reporting was
- Aizistral on Discord
