### ISSUE TITLE
Prevent reporting "have done sth I don't like"

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Aizistral-Studios/No-Chat-Reports#427]
### Idea

Disable the behavior reporting on 23w33a (and above).

禁用23w33a（及以上）的玩家行为举报。

### Reasoning

This is a really f*cking bad feature in Minecraft.

这是Minecraft中的一个该死的功能。

### Other Information

https://user-images.githubusercontent.com/86937725/261602915-13a0ea42-246f-4282-b662-7cef0c7e18ef.png

See the last line/看最后一行

The original page can be found on Minecraft Wiki/原页面可在Minecraft Wiki找到

This is a seperate issue, not duplicate with #426.

这是一个独立的议题，不和#426重复。

**Comment by Secret-chest** [comment]
Sadly this is not possible unless you get a new skin and nickname. However this is not mich of an issue as it looks like only the skin will be banned.

**Comment by Madis0** [comment]
To OP, I'm not so sure this is actually a good idea, to interfere with any report categories. I think the report category was meant as a distraction for users who try to make false reports, as Mojang does not seem to actually do something with such reports.

You posted in the wrong issue @Secret-chest

**Comment by IlyaTheSawmill** [comment]
It seems already done
