### ISSUE TITLE
Functionality enabled, even when mod is disabled in config

### ISSUE THREAD

**Issue by UltraBlackLinux** [Aizistral-Studios/No-Chat-Reports#433]
### Modloader

Quilt

### Minecraft Version

1.20.1

### Modloader Version

0.20.0-beta.11

### No Chat Reports Version

1.20.1-v2.2.2

### Bug Description

Even with the mod disabled in it's own config, I still get chat message validation errors on some servers. Chat message validation works as expected when the mod is just straight up not loaded

### Steps to Reproduce

1. Join e.g. zero.minr.org (fixed server name!)
2. Say something in chat
3. "Received chat packet with missing or invalid signature"

**Comment by Madis0** [comment]
May be a server-side issue, but I am unable to join aforementioned server anyway, seems to be down. Know any others with the same issue?

**Comment by UltraBlackLinux** [comment]
that is because I typed minor instead of minr smh

zero.minr.org

**Comment by Madis0** [comment]
Alright, tested the server out. It worked well on Fabric client (requested signatures when NCR enabled by the toggle, automatically fetched them when not), so this is probably a Quilt-specific issue of NCR. Possibly also related to #423

**Comment by UltraBlackLinux** [comment]
oh that seems identical to my issue, sorry for the duplicate
