### ISSUE TITLE
1.20.2 support

### ISSUE THREAD

**Issue by PukPukov** [Aizistral-Studios/No-Chat-Reports#436]
### Idea

1.20.2 support

**Comment by Madis0** [comment]
> Alright, it might take me a couple days to get to the port

- Aizistral

**Comment by Kichura** [comment]
Will this update have the ability to suppress the player name & skin reporting pages or is that out-of-scope?

**Comment by Madis0** [comment]
Out of scope, per #425 and #426

**Comment by PukPukov** [comment]
> Will this update have the ability to suppress the player name & skin reporting pages or is that out-of-scope?

Its impossible. Enjoy your cybergulag.

**Comment by Kichura** [comment]
> > Will this update have the ability to suppress the player name & skin reporting pages or is that out-of-scope?
> 
> Its impossible. Enjoy your cybergulag.

k, will go play card games.
