### ISSUE TITLE
Conflict with ViaFabricPlus

### ISSUE THREAD

**Issue by Brottweiler** [Aizistral-Studios/No-Chat-Reports#439]
### Modloader

Fabric

### Minecraft Version

1.20.2

### Modloader Version

Fabric: Loader 0.14.22 + API 0.89.2

### No Chat Reports Version

1.20.2-v2.3.1

### The latest.log File

https://mclo.gs/0powpQd

### Bug Description

Game crashes with ViaFabricPlus installed. Related issue https://github.com/ViaVersion/ViaFabricPlus/issues/255

### Steps to Reproduce

1. Install NoChatReports
2. Install ViaFabricPlus
3. Start game

**Comment by Madis0** [comment]
> Caused by: java.lang.NoSuchMethodException: com.mojang.authlib.yggdrasil.response.KeyPairResponse.viafabricplus_legacyKeySignature()

Hmm. I would blame VFP for this (maybe the mixin is too invasive?), but they apparently said NCR is at fault. I guess we'll wait for Aizistral's opinion 🤷

**Comment by florianreuth** [comment]
https://github.com/ViaVersion/ViaFabricPlus/commit/f88407f0bd38a43c24eb4d71a772bc1bddd70da7 I thought it was NCR doing some cursed stuff, but turns out my injection was just broken, fixed on ViaFabricPlus's site now and this issue can be closed.
