### ISSUE TITLE
The game crashed whilst rendering overlay

### ISSUE THREAD

**Issue by Lost0Neko** [Aizistral-Studios/No-Chat-Reports#440]
Game crashes on boot

[latest.log](https://github.com/Aizistral-Studios/No-Chat-Reports/files/12817713/latest.log)
[crash-2023-10-05_13.12.13-client.txt](https://github.com/Aizistral-Studios/No-Chat-Reports/files/12817715/crash-2023-10-05_13.12.13-client.txt)

Using Better MC [FORGE] - BMC4 modpack, NoChatReports-FORGE-1.20.1-v2.2.2, Minecraft 1.20.1

**Comment by Madis0** [comment]
Try deleting NCR config folder and restarting the game. Backup the folder if necessary

**Comment by YassaaaTU** [comment]
> Try deleting NCR config folder and restarting the game. Backup the folder if necessary

Deleting the NCR config folder doesn't help because the game crashes before reaching the point where it reads/creates the config files.

I removed the config and the game crashes without generating any config files.

[I have the same crash]

**Comment by katubug** [comment]
I am also having the same crash, after deleting the configs. Here is my crash report and latest.log: https://gist.github.com/katubug/f65d34d56851f0a28112d9ebd78b2a8c

The crash started occurring after I added a bunch of resourcepacks to be loaded by default, using the Resource Pack Overrides mod. However, I've had it a few times just using resourcepacks in general, before I configured that mod.

**Comment by Aizistral** [comment]
Not NCRs fault, see #471.
