### ISSUE TITLE
Literal string that could be converted to a translation key

### ISSUE THREAD

**Issue by James103** [Aizistral-Studios/No-Chat-Reports#45]
https://github.com/Aizistral-Studios/No-Chat-Reports/blob/ae263f13f7cb506c08b12acfecff61c5454bbc8e/src/main/java/com/aizistral/nochatreports/NoChatReports.java#L39

The above code, present in commit ae263f13f7cb506c08b12acfecff61c5454bbc8e, uses a literal string to show the kick reason, which is that the mod is not installed on the client but is required there by the server. This string could use some translations, which should make the mod a bit more accessible to international players.

**Comment by Aizistral** [comment]
In order to use translatable component the client has to have translation for it. The only way we can supply that translation is by having our mod installed on client, in which case player will not get kicked with this reason in the first place.

**Comment by Doenerstyle** [comment]
I'm not sure if people would want that, but you could add an option to change the message's language in the (serverside) config or even allow to configure a custom message through the config, like plugins often do.
It would be useful for servers that generally translate as much as they can into a specific language.

**Comment by Aizistral** [comment]
> I'm not sure if people would want that, but you could add an option to change the message's language in the (serverside) config or even allow to configure a custom message through the config, like plugins often do.

Make a separate issue on that, I will take care of it later.
