### ISSUE TITLE
Fails to load into game for whatever reason

### ISSUE THREAD

**Issue by ScoutTheSaneless** [Aizistral-Studios/No-Chat-Reports#450]
### Modloader

Forge

### Minecraft Version

1.20.1

### Modloader Version

NeoForge 47.1.81

### No Chat Reports Version

1.20.1-v2.2.2

### The latest.log File

https://pastebin.com/ifP6pFPe

### Bug Description

The game will crash upon start-up for whatever reason and NCR was at the top of the crashlog

### Steps to Reproduce

1. Run the game
2. Wait for the game to scream

### Other Information

Perhaps it is a mod conflict issue, but hell if I know wut it could be

**Comment by Aonodensetsu** [comment]
NCR 2.5.0 crashes with forge 48.1.0 on load with no other mods present

**Comment by Aizistral** [comment]
The original issue is not caused by NCR. NCR just ends up being the first mod to trigger an inevitable crash after a cascading set of exceptions. It seems that the primary cause is in `gg.essential.lib.okhttp3.internal.tls.CertificateChainCleaner`, whatever that is.

**Comment by Aizistral** [comment]
@Aonodensetsu please submit a separate bug report if you still experience the issue.
