### ISSUE TITLE
Crashes at startup for some reason

### ISSUE THREAD

**Issue by skel39eek66** [Aizistral-Studios/No-Chat-Reports#452]
### Modloader

Forge

### Minecraft Version

1.20.1

### Modloader Version

Forge: 47.18.2

### No Chat Reports Version

1.20.1-v2.2.2

### The latest.log File

https://gist.github.com/skel39eek66/93c4905006221d9e564716874954f648

### Bug Description

The game is crashing with NCR at startup for some reason, if install some mod (for example: Cull Leaves).
Tried to delete configs, but nothing changed...

Crash Report: https://gist.github.com/skel39eek66/f83b81d7eeebb6de58acc38c9e15ffc9

**Comment by 0xicl33n** [comment]
Same issue here. Was working before i updated a couple mods. It may have something to do with embeddium, they just released a new version today and both him and i have it

Crash report: https://gist.github.com/0xicl33n/a728f29054a7c16334f725709418f9cb

**Comment by P3rf3ctXZer0** [comment]
This has been fixed <- I am an alpha tester of embeddium and modernfix.
