### ISSUE TITLE
No chat reports makes the little blue rectangle disappear

### ISSUE THREAD

**Issue by QuercusFelis** [Aizistral-Studios/No-Chat-Reports#466]
### Modloader

Forge

### Minecraft Version

1.19.2

### Modloader Version

1.19.2-43.3.5

### No Chat Reports Version

Forge-1.19.2-v1.5.1

### Bug Description

I don't really know what the rectangle is supposed to do so it's possible this isn't strictly a bug, but I think it looks nice and would like for it to remain even when no chat reports is installed. Maybe it indicates that your messages are signed or something, but the rectangle is more important, I know what I have installed. 

Without No Chat Reports:
![image](https://github.com/Aizistral-Studios/No-Chat-Reports/assets/37717887/a223cb3a-03ad-44c7-ac0b-60171a40e40a)
With No Chat Reports:
![image](https://github.com/Aizistral-Studios/No-Chat-Reports/assets/37717887/36f22311-2c5c-4839-b665-436695a7c174)

**Comment by Madis0** [comment]
The rectangle is related to chat preview, which is a feature that existed in vanilla 1.19-1.19.2. 
I don't think NCR did anything specifically to it, but it might be related to the way indicators are hidden in 1.19.2.

So I'd suggest re-enabling signing indicators to see if that fixes it for you.

**Comment by Aizistral** [comment]
As @Madis0, you could try to re-enable message indicators in client config to see if that'll bring them back. But in any case, I don't plan on releasing any more updates for 1.19, so...
