### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by cqm3ron** [Aizistral-Studios/No-Chat-Reports#478]
### Idea

Title.

**Comment by xxxkingxl** [comment]
I am waiting for this to happen, Its one of the most important mods

**Comment by davepusey** [comment]
Also waiting on a 1.21.0 release please.

**Comment by jschenke488** [comment]
The game crashes when trying to launch 1.21 on Fabric. Not tested on Forge or NeoForge.

Crash Report: https://mclo.gs/tnkqlUJ
Versions:
- Fabric Loader 0.15.11
- Fabric API 0.100.1
- Java 21.0.3 (Azul Zulu)
- No Chat Reports 2.7.0

**Comment by HalfStony** [comment]
> The game crashes when trying to launch 1.21 on Fabric. Not tested on Forge or NeoForge.
> 
> Crash Report: https://mclo.gs/tnkqlUJ Versions:
> 
> * Fabric Loader 0.15.11
> * Fabric API 0.100.1
> * Java 21.0.3 (Azul Zulu)
> * No Chat Reports 2.7.0

Sorry, but that's not an issue. No Chat Reports is just not supported on 1.21.

**Comment by jschenke488** [comment]
I added the crash report to help find what needs to be changed for the update to happen. I know 2.7.0 is for 1.20.6.

Jun 17, 2024 8:28:58 AM HalfStony ***@***.***>:

> 
> The game crashes when trying to launch 1.21 on Fabric. Not tested on Forge or NeoForge.
> 
> Crash Report: https://mclo.gs/tnkqlUJ Versions:
> 
> * Fabric Loader 0.15.11
> * Fabric API 0.100.1
> * Java 21.0.3 (Azul Zulu)
> * No Chat Reports 2.7.0
> 
> Sorry, but that's not an issue. No Chat Reports is just not supported on 1.21.
>

**Comment by davepusey** [comment]
<strike>Managed to get it working in 1.21.0 on my own branch...</strike>

<strike>https://github.com/davepusey/No-Chat-Reports/tree/1.21-davepusey</strike>

EDIT: As there is now an official 1.21.0 release, I have deleted my branch.
