### ISSUE TITLE
Disconnect from Realms when player is killed with named weapon while encryption is enabled

### ISSUE THREAD

**Issue by Gamershy** [Aizistral-Studios/No-Chat-Reports#479]
### Modloader

Fabric

### Minecraft Version

1.21

### Modloader Version

Fabric Loader 1.15.11

### No Chat Reports Version

v2.8.0

### Modpack Info

https://www.mediafire.com/file/3zeyqbto2xdlhr3/Custom+Modpack+1.2.0.mrpack/file

### The latest.log File

https://mclo.gs/XVR73x9

### Bug Description

Whenever a player kills another player using a named weapon in realms, the game will disconnect all players with chat encryption enabled, across the entire realm. 

### Steps to Reproduce

Join any realm
Enable chat encryption
Give yourself a weapon with a custom name
kill any player using said weapon
You, and anyone else with chat encryption enabled, will be disconnected from the realm
Note: This sometimes causes authentication servers to not be reachable for a period of time, sometimes even requiring a client restart (or use of  another mod like Auth Me)

**Comment by DexrnZacAttack** [comment]
Can confirm this happens on normal servers too...

https://github.com/Aizistral-Studios/No-Chat-Reports/assets/60078656/105a2c01-4851-49bf-b647-35353cc26bfb

**Comment by DexrnZacAttack** [comment]
Can confirm, although it happens on any server.
It also requires the weapon to be enchanted.

Log: https://mclo.gs/XFs4dOo

https://github.com/Aizistral-Studios/No-Chat-Reports/assets/60078656/e0ce32de-49f2-47b4-8d30-0fbba564d7a9

**Comment by Sulferix** [comment]
basically the same issue occurs in the 1.20 version in heavily modded packs. this issue may affect all versions, please fix as nochatreports is required for safe usage of minecraft. 
![crash](https://github.com/user-attachments/assets/b4bb974e-025c-4aa5-95a5-1cec5f08d000)
1.20.1 using version v2.2.2
