### ISSUE TITLE
Allow servers to translate/alter the kick message for players without the mod

### ISSUE THREAD

**Issue by Doenerstyle** [Aizistral-Studios/No-Chat-Reports#48]
I think some servers would appreciate a (serverside) config option to translate this message:
https://github.com/Aizistral-Studios/No-Chat-Reports/blob/ae263f13f7cb506c08b12acfecff61c5454bbc8e/src/main/java/com/aizistral/nochatreports/NoChatReports.java#L39

My ideas would be to either add that message to the lang files and let the server choose which one to use **or** to allow them to configure a custom message through the config, like plugins often do, which offers far more customization.

You could also have **one** config option which can be used for **both**:
If it is, for example, set to "en_en", the default translation is used, if no lang file with that String was found (or the format is not xx_xx), the String itself will be the message. That'll only work as long as there aren't multiple serverside messages, of course.

This suggestion is based on #45.

**Comment by k9ur** [comment]
If it can be configured that joining the server requires installation of the mod, why is this a required feature?
They do operate differently, but ultimately achieve the same thing, unless I am missing something?

**Comment by LoganDark** [comment]
Servers don't have localizations without [LanguageHack](https://github.com/LoganDark/fabric-languagehack) which I haven't updated to 1.19 yet

**Comment by Doenerstyle** [comment]
I see. The (serverside) config should still be a good and viable option, however.

@otta8634 Sorry, I missed your comment. I don't quite understand what you mean, afaik that message is shown to clients without NCR if the server does have NCR installed and requires clients to do so, too. So I'm not sure what you think is "achieving the same thing"?
