### ISSUE TITLE
Heads aren't showed when seeing encryped messages with Chat Heads

### ISSUE THREAD

**Issue by IlyaTheSawmill** [Aizistral-Studios/No-Chat-Reports#482]
### Modloader

Fabric

### Minecraft Version

1.21

### Modloader Version

Fabric Loader 0.15.11 / API 0.100.4

### No Chat Reports Version

1.21-v2.8.0

### Bug Description

Heads are not showed if the message is encrypted with Chat Heads mod.
Maybe it is a bug of Chat Heads, so I also reported it to Chat Heads.

**Comment by Fourmisain** [comment]
Just a heads up: We're going to fix this on Chat Heads' end.

It's an issue of how Chat Heads sets a message's owner. Currently it just sets the owner on the first `GuiMessage` constructor call.
Decrypted messages [call the constructor again](https://github.com/Aizistral-Studios/No-Chat-Reports/blob/b255be32a640e490c9aaec4090e8ea5176db6b3b/src/main/java/com/aizistral/nochatreports/common/mixins/client/MixinChatComponent.java#L70) and thus do not get an owner.
There's tons of way to fix this on our end, it's just a question of which way to choose.

Issue link: https://github.com/dzwdz/chat_heads/issues/99

**Comment by Fourmisain** [comment]
Issue is fixed.
(Was apparently only a thing on 1.20.5+ or maybe 1.20.4 if I could test it)
