### ISSUE TITLE
Game keeps crashing upon trying to launch nochatreports for 1.20.4

### ISSUE THREAD

**Issue by lemons657** [Aizistral-Studios/No-Chat-Reports#483]
### Modloader

Fabric

### Minecraft Version

1.20.4

### Modloader Version

Fabric 0.15.7 / API 0.96.4

### No Chat Reports Version

2.5.0

### Bug Description

Mod has been working fine for over a month. haven't played minecraft for 3 days and upon trying to launch the game I get an error saying "failed to initialize game due to nochatreports". game launches fine without it and I need the mod for a server I'm playing on so any help regarding the topic would be greatly appreciated.

**Comment by Madis0** [comment]
You did not post logs as requested in the template, so we cannot help you. There is also a newer version of NCR available for 1.20.4 now, which you can try.
