### ISSUE TITLE
Network protocol error when accessing Paper 1.20 server (using ViaVersion)

### ISSUE THREAD

**Issue by MrPlantPlant** [Aizistral-Studios/No-Chat-Reports#493]
### Modloader

NeoForge

### Minecraft Version

1.21.3

### Modloader Version

Neoforge 21.3.7-beta

### No Chat Reports Version

1.21.3-3.0.0

### The latest.log File

https://mclo.gs/sAOg3HH

### Bug Description

When connecting to a Paper 1.20.1 server, using ViaVersion 5.1.1, I get an error message stating _network protocol error_, and the above disclosed disconnect log. When disabling NoChatReports it connects fine, leading me to believe the mod is the issue. 

### Other Information

I wasn't sure if the issue would be a duplicate of #492 but given some significant differences in versions I thought it'd be better to report separately rather than cause noise in the other issue

**Comment by shotadft** [comment]
Most likely a bug similar to #492.
