### ISSUE TITLE
Network protocol error

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Aizistral-Studios/No-Chat-Reports#494]
### Modloader

Fabric

### Minecraft Version

1.21.1

### Modloader Version

Fabric: Loader 0.16.7 + API 0.107.0

### No Chat Reports Version

1.21.1-v2.9.0

### Modpack Info

Additive 1.31.0+1.21.1 Fabric

### The latest.log File

https://mclo.gs/LbKoAGO

### Bug Description

Joining `summitofficial.minecraft.best` gets me a `network protocal issue`

### Steps to Reproduce

Join
see issue

### Other Information

I know others had made an issue like this, but in case my issue is somehow different or unique I posted it

I also used the following mods on their latest version: 
Chat Heads
MacOS Input Fixes
WaveyCapes
Better Add Server
Footprint Particle
CraftPresence
Architectury
Bobby
AppleSkin
Chat Patches
Controlling
CustomHud
No Chat Reports
Searchables
Keybind Fix
Presence Footsteps
UniLib
Placeholder API
ChatNotify
Xaero's Minimap
Xaero's World Map

**Comment by Madis0** [comment]
Can confirm, even with the NCR "enable mod" option set to OFF. However, the stack trace is identical to #492, so closing as duplicate.
