### ISSUE TITLE
Server list icons (client)

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#5]
Something like :warning: next to the server in server list when the server has `enforce-secure-profile` enabled.
Assuming it can be determined before connecting, that is.

**Comment by RaptaG** [comment]
Yeah I agree

**Comment by Aizistral** [comment]
Unfortunately, for that to work we have to somehow make the server provide the value of this property on query, which it obviously does not do on its own. And if we have the mod installed on server - `enforce-secure-profile` will be automatically disabled anyways.
