### ISSUE TITLE
Create a repository mirror to prevent code censorship

### ISSUE THREAD

**Issue by Mhowser** [Aizistral-Studios/No-Chat-Reports#51]
I'm worried that Microsoft may decide to take down this project in the future. Since Github is owned by Microsoft, this is a trivial thing for them to do. So I suggest creating a mirror of this project to another site. Gitlab, BitBucket, & Sourceforge are some examples.

**Comment by ghost** [comment]
It's kinda unlikely. Even if they make up an excuse to take it down, the developer would still have the code locally and it's gonna be the CurseForge/Modrinth situation once again - Microsoft would just get more hate on itself and more people will know about the mod.

nontheless it's a good idea to have some sort of backups in case something like that happens

**Comment by Aizistral** [comment]
Done.
