### ISSUE TITLE
Immense game start up delay.

### ISSUE THREAD

**Issue by KateReller** [Aizistral-Studios/No-Chat-Reports#57]
This making me pull my hair out, but something is creating a five to TEN minute delay on start up (before the minecraft window pops up). Disabling this mod removes this delay.

https://paste.ee/p/b5Kzk#s=0&l=323

Line 323 shows the delay.

**Comment by Aizistral** [comment]
Unfortunately, I cannot reproduce this. This seems to be a problem involving some other mod in your modpack, as I do not encounter it with just NCR itself. Try to split your modpack in two before you narrow it down to specific mod(s) that are causing this issue when combined with NCR.

**Comment by nyxiereal** [comment]
Try using smoothboot
