### ISSUE TITLE
Backport some changes to 1.19

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#61]
1.19.1 snapshot versions of the mod have received several useful changes, including the whitelist and chat indicator. These would make sense to get backported to 1.19 as well at some point, as some clients/servers are probably afraid to update to 1.19.1 at all.

**Comment by Aizistral** [comment]
This is not a high priority at this point, especially since those new features were largely motivated by the fact `enforce-secure-profile` was defaulted to `true`, but we can do a backport eventually.

**Comment by Aizistral** [comment]
Due to low relevance and high probability that 1.19-format signatures will not even be considered valid for reports, I suppose this can be closed.
