### ISSUE TITLE
Hide clientside report triangle

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#62]
An option to hide the client-side report triangle would make sense. Right now you've tied it to when the mod exists on the server as well, but a separate option for the client only would be nice.

**Comment by Aizistral** [comment]
> Right now you've tied it to when the mod exists on the server

Well, I did that since it appeared to me to be strange that mod would limit player in a way that the rest of the server does not have to be compliant with. But sure, I can do an option
