### ISSUE TITLE
Seeing own chat despite client-side security setting

### ISSUE THREAD

**Issue by Foxite** [Aizistral-Studios/No-Chat-Reports#64]
I'm testing this mod on the server but I can't tell if it works or not, I have a vanilla client with "Only show secure chat" turned on, and I can see my own chat despite the mod being installed on the server.

Does this mean the mod isn't working or does the client show its own chat messages regardless of signature status? I also don't see a flag indicating the signature is invalid, if the option is turned off, which I was told there would be.

Unfortunately I don't have a second minecraft account to test this with.

I'm using pre3 with the latest build (43 minutes ago) of your mod.

**Comment by Aizistral** [comment]
It happens because player messages are automatically converted to system messages when relayed by server (can be disabled in config). System messages don't have any signatures and clients never try to verify them. I did not update mod description to reflect this yet, but I will.
