### ISSUE TITLE
"Only Show Secure Chat" button should be grayed out

### ISSUE THREAD

**Issue by WVam** [Aizistral-Studios/No-Chat-Reports#66]
Since the setting cannot be changed, the button shouldn't appear clickable. Instead it should be grayed out, like the "Difficulty" button in the world creation screen when selecting Gamemode: Hardcore.

**Comment by Aizistral** [comment]
I wish I could do that, but amount of abstraction that goes into those option menus makes it impossible to design an elegant solution. That's not to say it's impossible at all, just that I'm not happy with amout of coremodding and questionable design choices that would have to go into adding this small visual neatness. But pull requests are always open in case someone can manage a reasonable solution I didn't think of.
