### ISSUE TITLE
Explain timestamp scrambler

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#67]
As of 1.3.2 there is a timestamp scrambler in the mod. However, there is no explanation on the mod listing about how does it work, please add it.

**Comment by Aizistral** [comment]
Frankly we need better documentation for other things as well. I'll get to it eventually.

**Comment by Madis0** [comment]
Doesn't matter, pre4 fixed this haha.

**Comment by Aizistral** [comment]
It didn't (:

**Comment by Aizistral** [comment]
Although pre-release 4 does not actually prevent scrambler from working yet, we have reasons to speculate that it will be rendered ineffective indirectly as of the next pre-release. The implementation behind it is also adds complications to ongoing maintenance, so I will probably remove it from the mod for now, and re-add later if somehow it will still be useful.
