### ISSUE TITLE
Open To LAN?

### ISSUE THREAD

**Issue by SoniEx2** [Aizistral-Studios/No-Chat-Reports#71]
Is this mod compatible with Open To LAN and is that officially supported?

**Comment by Aizistral** [comment]
You mean vanilla option to open your singleplayer world to LAN, or what?

**Comment by SoniEx2** [comment]
yes the built-in open to lan button.

**Comment by Aizistral** [comment]
...why would it be incompatible. Lan servers are not very different from dedicated servers in this regard.

**Comment by SoniEx2** [comment]
it didn't seem officially supported. has it been tested for that? it's also not written anywhere on the mod.

**Comment by Aizistral** [comment]
There's absolutely no reason for it to not work. Considerations you have to do for LAN server are the same as for dedicated one. I might document it later.

**Comment by SoniEx2** [comment]
you can say "I didn't test that use-case", it's not gonna harm you...

**Comment by Aizistral** [comment]
If you really wanna hear that - yes, I didn't test the use-case. I still can confidently say there is nothing different about such use-case that would make it not work as it does in use-case of dedicated server.
