### ISSUE TITLE
Send reports to server admins instead of Mojang

### ISSUE THREAD

**Issue by abasgames** [Aizistral-Studios/No-Chat-Reports#73]
if possible add it as option in server side
i know this mod called no-chats-reports
maybe create new fork for this specific feature ?

**Comment by Aizistral** [comment]
I will implement this later. For now the focus is on more critical features, and on fast update to 1.19.1 once that drops.

**Comment by Danjhop4** [comment]
Add a way for servers to ignore bans and bypass them in game

**Comment by Danjhop4** [comment]
Your licence is rude but I like it

**Comment by NotAHolyPerson** [comment]
this probably would be only possible if the mod is installed both sides

**Comment by Aizistral** [comment]
> this probably would be only possible if the mod is installed both sides

Yes. But since the mod can be configured to demand installation on every joining client when operated on server side - it should not be a big problem.

**Comment by Secret-chest** [comment]
I think it should be a separate mod. It should also allow changing context lines, report categories etc. in the config

**Comment by Danjhop4** [comment]
> I think it should be a separate mod. It should also allow changing context lines, report categories etc. in the config

Good idea got banned from bug discord for showing that’s true

**Comment by Aizistral** [comment]
What is "bug discord"?

**Comment by Danjhop4** [comment]
The mojang bug tracker has a dis cord

**Comment by amelia-bartlett** [comment]
I like it.
There would still need to be a warning about chat reporting possibility on the server, but this is how the chat reporting system should have been implemented from the start.

**Comment by IlyaTheSawmill** [comment]
It shouldn't be based on the signing system.

**Comment by abasgames** [comment]
> I will implement this later. For now the focus is on more critical features, and on fast update to 1.19.1 once that drops.

Hey Aizistral where can i contact you in private 
I found a way to allow banned account to join servers but it requires changes on the server side it won't be a cheating/security risk at all i will explain in details in private if possible

**Comment by Aizistral** [comment]
@abasgames sure. You can add and DM me on Discord, name's `aizistral`.
