### ISSUE TITLE
Merge reload with vanilla refresh

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#74]
As of v1.4.1 there seems to be a reload button in the multiplayer view. While it could be useful in some cases, I don't think it needs a separate visible button at the moment.
How about merging it with the vanilla refresh button so it does both things at once?

**Comment by Aizistral** [comment]
I fear that will not be very intuitive.

**Comment by Madis0** [comment]
Then it could be merged with it's _function_, aka reload NCR's config every time multiplayer server list is loaded by any means. 
Don't see how that could cause any harm, considering that NCR's config is a small local JSON...

**Comment by Aizistral** [comment]
Well, how is that going to be more intuitive?

**Comment by Madis0** [comment]
E.g. change this in the description
> Configuration file is named NoChatReports.json and is located in default config folder.

to

> Configuration file is named NoChatReports.json and is located in default config folder. It can be changed while the game is running and it will take effect as soon as the player loads the multiplayer server list. 

No more visual cues are needed in-game, as I would not expect many players to edit the config in the first place.

**Comment by Aizistral** [comment]
That description is only visible for unsafe servers. If I want fancy button - I will have fancy button. Leave it alone.
