### ISSUE TITLE
ban bypass 

### ISSUE THREAD

**Issue by Danjhop4** [Aizistral-Studios/No-Chat-Reports#76]
Add a way for servers to bypass the bans and on the game so mojang can’t do anything and hide the warnings or allow people to report anyways so mojang gets a ton of banned people reported

**Comment by abasgames** [comment]
> 

i don't think thats is possible because mojang well simply tells the server thats the account is unauthenticated like a cracked game

**Comment by ghost** [comment]
hide the warnings is something that can be done and has already been done

**Comment by Danjhop4** [comment]
Ok

**Comment by Danjhop4** [comment]
Make the server check for can and override with the offline mode for that player

**Comment by Aizistral** [comment]
There is no simple way to implement this, and less simple ways are out of scope for this project. I would want it to remain focused on providing preventive measures.
