### ISSUE TITLE
Whitelisted servers keep assumptions again

### ISSUE THREAD

**Issue by Madis0** [Aizistral-Studios/No-Chat-Reports#82]
#43 but on v1.4.2. Game restart fixes it, relogging or the refresh button will not.

**Comment by Aizistral** [comment]
I cannot reproduce this. Describe your exact steps.

**Comment by Madis0** [comment]
1. Set up a server with online-mode: true, enforce-secure-profile: true
2. Enter the server, confirm the prompt and check the checkbox
3. Verify the icon in chat (red)
4. Leave the server
5. Set the server to online-mode: false, restart it
6. Join the server
7. Verify the icon in chat (should be yellow but is red)

**Comment by Aizistral** [comment]
I've done the same steps as you and icon is yellow in my case after all this, just as it should be. Did you do your tests with vanilla server?

**Comment by Madis0** [comment]
Yes, a vanilla 1.19.1-pre3 server.

**Comment by Aizistral** [comment]
Then I really have no idea what's happening in your instance. I noticed a small potential issue in my state management that might arise when you get disconnected by server instead of leaving normally, but from your words that's not your case.

**Comment by Aizistral** [comment]
Anyways, try again in v1.4.3, maybe that's somehow related after all. Also test the cases for disabling `online-mode` and `enforce-secure-profile` separately.

**Comment by Madis0** [comment]
Seems to work now.
