### ISSUE TITLE
Add new version build for 1.19

### ISSUE THREAD

**Issue by minecraft-go-new** [Aizistral-Studios/No-Chat-Reports#86]
You add save indicator in new versions for 1.19.1, but because there no new mod versions for 1.19 there is no save indicator on 1.19
Can you please make build of new version for 1.19 with save indicator ?
P.s. by save indicator  I mean chat_status_icons.png

**Comment by Aizistral** [comment]
This already goes as part of #61. I will backport new features eventually.
