### ISSUE TITLE
Mod the server to allow players without signature

### ISSUE THREAD

**Issue by Secret-chest** [Aizistral-Studios/No-Chat-Reports#88]
Like disabling `enforce-secure-profile` but Mojamg cannot disallow it.

**Comment by obj-obj** [comment]
This is what the mod already does serverside

**Comment by Aizistral** [comment]
Yeah, that was implemented from the start.

**Comment by Secret-chest** [comment]
Ah ok. So if mojang enforces enforce secure profile, then it will still work?

**Comment by Aizistral** [comment]
You mean if they remove the option altogether? I'll have to make some adjustments to the codebase most probably, but yeah, it will work.
