### ISSUE TITLE
Add a way to edit chat reports to work offline and edit them

### ISSUE THREAD

**Issue by Danjhop4** [Aizistral-Studios/No-Chat-Reports#89]
Want to prove its badly designed got banned from bug discord over it

**Comment by Aizistral** [comment]
I don't understand what you are trying to say and suggest.

**Comment by fire12324344** [comment]
Already exists in another mod and isn't relevant to this project lmao.

**Comment by Aizistral** [comment]
Out of scope, Gaslight already does that as separate mod. I will release a standalone tool for simply intercepting chat reports later, but it will not be a part of this mod.
