### ISSUE TITLE
Hide the "Chat messages cannot be verified" toast

### ISSUE THREAD

**Issue by Kichura** [Aizistral-Studios/No-Chat-Reports#92]
Starting in 1.19.1-rc2, A new toast has been added for whenever the player logs on to older servers / 1.19.1 servers that have the secure-chat-only mode disabled, the toast will appear over and over again until the secure-chat-only mode is re-enabled or clients are downgraded instead,

Mostly this can be ignored but for specific people may turn out annoying in some scenarios.

**Comment by Aizistral** [comment]
I have already addressed this in build 1.19.1-rc2-v1.6.0.
